#!/usr/bin/env python3
"""Generate roomrom_ow_palette.{c,h} from nes_ow_palram_static.json.

Source: extract_ow_palram_from_rom.py extracts the level-default OW PALRAM
(32 bytes) from each NES ROM's LevelInfoOW data block. We emit it as
g_roomrom_ow_palram[2][32] (map index 0 = orig, 1 = redux).

The renderer indexes this directly; per-room sub-pal-3 patches (rocks,
armos, gravestones) are a future refinement applied at room-load time.

UW palettes already live in g_uw_room_palette[636][32] from the existing
runtime BizHawk capture path (more detailed than static .dat extraction
since UW patches sub-pal-3 per-room). UW path unchanged.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
INPUT = ROOT / "out" / "nes_ow_palram_static.json"
OUT_C = ROOT / "src" / "roomrom_ow_palette.c"
OUT_H = ROOT / "src" / "roomrom_ow_palette.h"


def fail(msg: str) -> None:
    print(f"gen_bg_palette_blob: FAIL: {msg}", file=sys.stderr)
    sys.exit(1)


def main() -> None:
    if not INPUT.exists():
        fail(f"missing {INPUT}; run extract_ow_palram_from_rom.py first")
    payload = json.loads(INPUT.read_text(encoding="utf-8"))
    rows: list[list[int]] = []
    for label in ("orig", "redux"):
        if label not in payload:
            fail(f"{INPUT}: missing key {label!r}")
        pr = payload[label]
        if len(pr) != 32:
            fail(f"{label}: PALRAM len {len(pr)} != 32")
        if pr[0] != 0x0F:
            fail(f"{label}: PALRAM[0] = 0x{pr[0]:02X} != 0x0F")
        rows.append(pr)

    h_lines = [
        "/* Generated by RoomRom/tools/gen_bg_palette_blob.py. Do not edit. */",
        "#ifndef ROOMROM_OW_PALETTE_H",
        "#define ROOMROM_OW_PALETTE_H",
        "",
        "/* g_roomrom_ow_palram[map][i] holds NES Overworld PALRAM bytes",
        " * (i in [0..31]: bytes 0..15 = BG sub-pals, 16..31 = SPR sub-pals).",
        " * map index 0 = original, 1 = redux. */",
        "extern const unsigned char g_roomrom_ow_palram[2][32];",
        "",
        "#endif",
    ]
    OUT_H.write_text("\n".join(h_lines) + "\n", encoding="utf-8")

    c_lines = [
        "/* Generated by RoomRom/tools/gen_bg_palette_blob.py. Do not edit. */",
        "#include \"roomrom_ow_palette.h\"",
        "",
        "const unsigned char g_roomrom_ow_palram[2][32] = {",
    ]
    labels = ("orig", "redux")
    for label, row in zip(labels, rows):
        row_hex = ", ".join(f"0x{b:02X}" for b in row)
        c_lines.append(f"    /* {label} */ {{ {row_hex} }},")
    c_lines.append("};")
    OUT_C.write_text("\n".join(c_lines) + "\n", encoding="utf-8")

    print(f"wrote {OUT_H}")
    print(f"wrote {OUT_C}")


if __name__ == "__main__":
    main()
