#!/usr/bin/env python3
"""Convert a 4096-byte NES PPU $0000-$0FFF pattern-table dump into a
Genesis 4bpp CHR C array.

Input:  RoomRom/out/nes_uw_chr_redux.bin   (256 NES tiles, 16 bytes each)
Output: RoomRom/src/redux_uw_bg.c           (256 Genesis tiles, 32 bytes each)

NES 2bpp -> Genesis 4bpp conversion (low 2 bits of pixel from NES).

Emits array `redux_uw_bg_chr[8192]` and size constant.
Renderer maps NES tile N -> Genesis VRAM tile (N + UW_VDP_TILE_BASE);
loading these 256 tiles at VRAM tile base 1 keeps that mapping
unchanged from the vanilla layout.
"""

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
BIN_PATH = ROOT / "RoomRom" / "out" / "nes_uw_chr_redux.bin"
OUT_C = ROOT / "RoomRom" / "src" / "redux_uw_bg.c"

NES_TILE_BYTES = 16
GEN_TILE_BYTES = 32
NUM_TILES = 256
TOTAL_GEN_BYTES = NUM_TILES * GEN_TILE_BYTES  # 8192


def nes_tile_to_genesis(nes: bytes) -> bytes:
    """Convert one NES 2bpp 8x8 (16 bytes) -> Genesis 4bpp (32 bytes)."""
    if len(nes) != NES_TILE_BYTES:
        raise ValueError(f"expected {NES_TILE_BYTES} bytes, got {len(nes)}")
    out = bytearray(GEN_TILE_BYTES)
    for row in range(8):
        p0 = nes[row]
        p1 = nes[row + 8]
        # Each row: 4 output bytes, 2 pixels per byte (high nibble = left).
        for col_pair in range(4):
            bit_lo = 7 - (col_pair * 2)
            bit_hi = 7 - (col_pair * 2 + 1)
            left = ((p0 >> bit_lo) & 1) | (((p1 >> bit_lo) & 1) << 1)
            right = ((p0 >> bit_hi) & 1) | (((p1 >> bit_hi) & 1) << 1)
            out[row * 4 + col_pair] = (left << 4) | right
    return bytes(out)


def main() -> int:
    if not BIN_PATH.exists():
        sys.exit(f"FATAL: {BIN_PATH} not found. Run probe_nes_uw_chr_dump.lua first.")
    raw = BIN_PATH.read_bytes()
    if len(raw) != NES_TILE_BYTES * NUM_TILES:
        sys.exit(f"FATAL: {BIN_PATH} is {len(raw)} bytes, expected {NES_TILE_BYTES * NUM_TILES}")

    out = bytearray()
    for t in range(NUM_TILES):
        nes_tile = raw[t * NES_TILE_BYTES:(t + 1) * NES_TILE_BYTES]
        out.extend(nes_tile_to_genesis(nes_tile))

    if len(out) != TOTAL_GEN_BYTES:
        sys.exit(f"FATAL: produced {len(out)} bytes, expected {TOTAL_GEN_BYTES}")

    lines = [
        "/* Auto-generated by RoomRom/tools/gen_redux_uw_bg.py - do not edit. */",
        "",
        f"const unsigned long redux_uw_bg_chr_size = {TOTAL_GEN_BYTES}UL;",
        f"const unsigned char redux_uw_bg_chr[{TOTAL_GEN_BYTES}] = {{",
    ]
    for off in range(0, TOTAL_GEN_BYTES, 16):
        chunk = out[off:off + 16]
        lines.append("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
    lines.append("};")
    lines.append("")
    OUT_C.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT_C} ({TOTAL_GEN_BYTES} bytes, {NUM_TILES} tiles)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
