#!/usr/bin/env python3
from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
ROOMROM_SRC = ROOT / "RoomRom" / "src"
REDUX_OW = ROOT / "Zelda1-Redux" / "code" / "gameplay" / "overworld_screens.asm"
REDUX_OW_CHR = ROOT / "Zelda1-Redux" / "code" / "gfx" / "data_02b.bin"
REDUX_SECRET_CHR = ROOT / "Zelda1-Redux" / "code" / "gfx" / "OverworldAssets.bin"
REDUX_AUTOMAP_CHR = ROOT / "Zelda1-Redux" / "code" / "gameplay" / "automap_tiles.bin"
ORIGINAL_OW_C = ROOT / "data" / "rooms" / "overworld.c"
# Builder input: the same byte strings located in the user's Redux ROM by
# tools/builder/rom_blobs.py (RoomRom/data/redux_sources.template.json).
# Used when the Zelda1-Redux source tree is not present.
REDUX_SRC = ROOT / "RoomRom" / "out" / "redux_src"

OW_ATTRS_A_OFFSET = 0
OW_ATTRS_B_OFFSET = 128
OW_LAYOUTS_OFFSET = 1166
OW_HEAP_BLOB_OFFSET = 3150

HEAP_LABELS = [
    "column_definitions",
    "l_17955",
    "l_17986",
    "l_179C8",
    "l_17A0C",
    "l_17A3E",
    "l_17A7A",
    "l_17AB5",
    "l_17AF0",
    "l_17B2E",
    "l_17B6F",
    "l_17BB4",
    "l_17BF1",
    "l_17C27",
    "l_17C69",
    "l_17C9D",
]


def c_bytes(path: Path) -> list[int]:
    text = path.read_text(encoding="ascii")
    return [int(x, 16) for x in re.findall(r"0x([0-9a-fA-F]{2})", text)]


def parse_db_lines(text: str) -> list[int]:
    values: list[int] = []
    for raw in text.splitlines():
        line = raw.split("//", 1)[0].strip()
        if not line.startswith("db "):
            continue
        for token in line[3:].split(","):
            token = token.strip()
            if not token:
                continue
            if not token.startswith("$"):
                raise ValueError(f"unsupported db token: {token}")
            values.append(int(token[1:], 16))
    return values


def parse_between(text: str, start: str, end: str) -> list[int]:
    begin = text.index(start)
    finish = text.index(end, begin)
    return parse_db_lines(text[begin:finish])


def parse_label_block(text: str, label: str, following_labels: list[str]) -> list[int]:
    start = text.index(label + ":")
    ends = [text.find(next_label + ":", start + 1) for next_label in following_labels]
    ends += [text.find("fillto", start + 1), text.find("// Dungeon screens", start + 1)]
    candidates = [end for end in ends if end != -1]
    if not candidates:
        raise ValueError(f"could not find end for {label}")
    return parse_db_lines(text[start:min(candidates)])


def nes_tile_to_genesis(nes_tile: bytes) -> bytes:
    out = bytearray(32)
    for row in range(8):
        p0 = nes_tile[row]
        p1 = nes_tile[row + 8]
        for px in range(8):
            bit = 7 - px
            color = ((p1 >> bit) & 1) << 1 | ((p0 >> bit) & 1)
            idx = row * 4 + px // 2
            if px & 1:
                out[idx] |= color
            else:
                out[idx] |= color << 4
    return bytes(out)


def convert_chr(nes_data: bytes) -> bytes:
    if len(nes_data) % 16:
        raise ValueError("NES CHR data is not tile-aligned")
    out = bytearray()
    for idx in range(0, len(nes_data), 16):
        out.extend(nes_tile_to_genesis(nes_data[idx:idx + 16]))
    return bytes(out)


def emit_c_array(name: str, values: list[int] | bytes, generated_by: str) -> str:
    data = bytes(values)
    lines = [
        f"/* Auto-generated by {generated_by} - do not edit. */",
        f"const unsigned long {name}_size = {len(data)}UL;",
        f"const unsigned char {name}[{len(data)}] = {{",
    ]
    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        comma = "" if i + 16 >= len(data) else ","
        lines.append("    " + ", ".join(f"0x{b:02x}" for b in chunk) + comma)
    lines.append("};")
    lines.append("")
    return "\n".join(lines)


def emit_u16_array(name: str, values: list[int], generated_by: str) -> str:
    lines = [
        f"/* Auto-generated by {generated_by} - do not edit. */",
        f"const unsigned short {name}[{len(values)}] = {{",
        "    " + ",".join(str(v) for v in values),
        "};",
        "",
    ]
    return "\n".join(lines)


def load_sources() -> tuple[list[int], list[list[int]], bytes, bytes, bytes]:
    """(layouts+caves, 16 column heaps, OW BG CHR, secret CHR, automap CHR)."""
    if not REDUX_OW.exists():
        rd = lambda name: (REDUX_SRC / name).read_bytes()
        heaps = [list(rd(f"column_heap_{i:02d}.bin")) for i in range(len(HEAP_LABELS))]
        return (list(rd("overworld_column_data.bin")), heaps, rd("data_02b.bin"),
                rd("OverworldAssets.bin"), rd("automap_tiles.bin"))
    redux_text = REDUX_OW.read_text(encoding="utf-8")
    layouts = parse_between(redux_text, "overworld_column_data:", "//\tColumn Definitions")
    heaps = [parse_label_block(redux_text, label, HEAP_LABELS[i + 1:])
             for i, label in enumerate(HEAP_LABELS)]
    return (layouts, heaps, REDUX_OW_CHR.read_bytes(), REDUX_SECRET_CHR.read_bytes(),
            REDUX_AUTOMAP_CHR.read_bytes())


def main() -> None:
    original = c_bytes(ORIGINAL_OW_C)
    layouts_and_caves, heap_blocks, ow_chr, secret_chr, automap_chr = load_sources()
    if len(layouts_and_caves) != OW_HEAP_BLOB_OFFSET - OW_LAYOUTS_OFFSET:
        raise ValueError(
            f"Redux layout/cave span is {len(layouts_and_caves)} bytes; "
            f"expected {OW_HEAP_BLOB_OFFSET - OW_LAYOUTS_OFFSET}"
        )

    heap_offsets: list[int] = []
    heap: list[int] = []
    for block in heap_blocks:
        heap_offsets.append(len(heap))
        heap.extend(block)

    redux = original[:OW_LAYOUTS_OFFSET]
    redux.extend(layouts_and_caves)
    redux.extend(heap)

    # Overworld palette attribute changes from Zelda1-Redux/code/gameplay/overworld_screens.asm.
    redux[OW_ATTRS_A_OFFSET + 0x22] = 0x70
    redux[OW_ATTRS_A_OFFSET + 0x32] = 0x00
    redux[OW_ATTRS_A_OFFSET + 0x33] = 0xA0
    redux[OW_ATTRS_B_OFFSET + 0x32] = 0x00

    chr_data = convert_chr(ow_chr)
    if len(chr_data) != 4160:
        raise ValueError(f"Redux overworld CHR converted to {len(chr_data)} bytes; expected 4160")
    secret_chr_data = convert_chr(secret_chr)
    if len(secret_chr_data) != 384:
        raise ValueError(
            f"Redux visible-secret CHR converted to {len(secret_chr_data)} bytes; expected 384"
        )
    automap_chr_data = convert_chr(automap_chr)
    if len(automap_chr_data) != 1024:
        raise ValueError(
            f"Redux automap CHR converted to {len(automap_chr_data)} bytes; expected 1024"
        )

    ROOMROM_SRC.mkdir(parents=True, exist_ok=True)
    (ROOMROM_SRC / "redux_overworld.c").write_text(
        emit_c_array("rooms_overworld_redux", redux, "RoomRom/tools/gen_redux_roomrom.py")
        + emit_u16_array(
            "rooms_overworld_redux_heap_offsets",
            heap_offsets,
            "RoomRom/tools/gen_redux_roomrom.py",
        ),
        encoding="ascii",
        newline="\n",
    )
    (ROOMROM_SRC / "redux_overworld_bg.c").write_text(
        emit_c_array("redux_overworld_bg_chr", chr_data, "RoomRom/tools/gen_redux_roomrom.py")
        + emit_c_array(
            "redux_overworld_secret_chr",
            secret_chr_data,
            "RoomRom/tools/gen_redux_roomrom.py",
        ),
        encoding="ascii",
        newline="\n",
    )
    (ROOMROM_SRC / "redux_hud_chr.c").write_text(
        emit_c_array("redux_automap_chr", automap_chr_data, "RoomRom/tools/gen_redux_roomrom.py"),
        encoding="ascii",
        newline="\n",
    )
    print(f"wrote RoomRom Redux overworld: {len(redux)} bytes, heap {len(heap)} bytes")
    print("wrote RoomRom Redux overworld CHR: 4160 bytes")
    print("wrote RoomRom Redux visible-secret CHR: 384 bytes")
    print("wrote RoomRom Redux automap CHR: 1024 bytes")


if __name__ == "__main__":
    main()
