#!/usr/bin/env python3
"""Generate RoomRom UW NT blob from RoomRom/out/nes_uw_aggregate.json.

Replaces the legacy two-file `nes_uw_warp_v2.json`/`nes_uw_warp_redux.json`
inputs. Consumes only the verified aggregate produced by
verify_uw_aggregate.py. Each captured (rom, quest, level, room_id)
becomes one blob entry.

Schema migration (3-tuple -> 4-tuple):
  Old: g_uw_room_index[][3] = {map_id, level, room_id}
  New: g_uw_room_index[][4] = {map_id, quest, level, room_id}

The runtime consumer in RoomRom/src/uw_room_render_roomrom.c filters on
all four fields (map -> rom, quest, level, room).

Emits:
  RoomRom/src/uw_room_blob.c containing:
    - g_uw_room_count
    - g_uw_room_index[][4]   : (map_id, quest, level, room_id)
    - g_uw_room_nt[][22*32]  : play-area nametable (NT rows 8..29)
    - g_uw_room_attr[][64]   : full attribute table $23C0..$23FF
    - g_uw_room_palette[][32]: NES PALRAM

Sort order: (map_id, quest, level, source_block, room_id).

Fail conditions:
  - Aggregate missing.
  - Same (rom, quest, level, room_id) appears with conflicting hashes
    across different source_blocks (would silently pick one); blob gen
    aborts in that case.
"""

from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
AGG_PATH = ROOT / "RoomRom" / "out" / "nes_uw_aggregate.json"
OUT_C = ROOT / "RoomRom" / "src" / "uw_room_blob.c"

PLAY_NT_TOP = 8
PLAY_ROWS = 22
PLAY_COLS = 32


def hash_entry(e: dict) -> str:
    nt_bytes = bytes(b for row in e["nt"] for b in row)
    attr_bytes = bytes(e["attr"])
    pal_bytes = bytes(e["palram"])
    h = hashlib.sha256()
    h.update(nt_bytes); h.update(attr_bytes); h.update(pal_bytes)
    return h.hexdigest()


def emit_c(entries: list[dict], out_path: Path) -> None:
    lines: list[str] = []
    lines.append("/* Auto-generated by RoomRom/tools/gen_uw_blob.py - do not edit. */")
    lines.append("")
    lines.append("#include \"uw_room_blob.h\"")
    lines.append("")
    n = len(entries)
    lines.append(f"const unsigned short g_uw_room_count = {n}u;")
    lines.append("")
    lookup = [[[[0 for _ in range(128)] for _ in range(10)] for _ in range(3)] for _ in range(2)]
    for idx, e in enumerate(entries):
        mid = e["map_id"]
        q = e["quest"]
        lvl = e["level"]
        rid = e["room_id"]
        if mid < 2 and q < 3 and lvl < 10 and rid < 128:
            lookup[mid][q][lvl][rid] = idx + 1
    lines.append("const unsigned short g_uw_room_lookup[2][3][10][128] = {")
    for mid in range(2):
        lines.append("    {")
        for q in range(3):
            lines.append("        {")
            for lvl in range(10):
                lines.append("            {")
                vals = lookup[mid][q][lvl]
                for i in range(0, 128, 8):
                    lines.append("                " + ", ".join(f"{v}u" for v in vals[i:i + 8]) + ",")
                lines.append("            },")
            lines.append("        },")
        lines.append("    },")
    lines.append("};")
    lines.append("")
    lines.append(f"const unsigned char g_uw_room_index[{max(n,1)}][4] = {{")
    for e in entries:
        mid = e["map_id"]
        q = e["quest"]
        lvl = e["level"]
        rid = e["room_id"]
        lines.append(f"    {{ {mid:#04x}, {q:#04x}, {lvl:#04x}, {rid:#04x} }},")
    if n == 0:
        lines.append("    { 0, 0, 0, 0 }, /* placeholder */")
    lines.append("};")
    lines.append("")
    lines.append(f"const unsigned char g_uw_room_nt[{max(n,1)}][{PLAY_ROWS * PLAY_COLS}] = {{")
    for e in entries:
        nt = e["nt"]
        lines.append("    {")
        for r in range(PLAY_ROWS):
            row = nt[PLAY_NT_TOP + r]
            byte_strs = ", ".join(f"{b:#04x}" for b in row)
            lines.append(f"        {byte_strs},")
        lines.append("    },")
    if n == 0:
        lines.append("    { 0 },")
    lines.append("};")
    lines.append("")
    lines.append(f"const unsigned char g_uw_room_attr[{max(n,1)}][64] = {{")
    for e in entries:
        attr = e.get("attr") or ([0] * 64)
        if len(attr) < 64:
            attr = list(attr) + [0] * (64 - len(attr))
        byte_strs = ", ".join(f"{b:#04x}" for b in attr[:64])
        lines.append(f"    {{ {byte_strs} }},")
    if n == 0:
        lines.append("    { 0 },")
    lines.append("};")
    lines.append("")
    lines.append(f"const unsigned char g_uw_room_palette[{max(n,1)}][32] = {{")
    for e in entries:
        pal = e["palram"]
        byte_strs = ", ".join(f"{b:#04x}" for b in pal)
        lines.append(f"    {{ {byte_strs} }},")
    if n == 0:
        lines.append("    { 0 },")
    lines.append("};")
    lines.append("")
    out_path.write_text("\n".join(lines) + "\n")


def main(argv: list[str]) -> int:
    if not AGG_PATH.exists():
        sys.stderr.write(
            f"FATAL: aggregate dump missing: {AGG_PATH}\n"
            "Run: python RoomRom/tools/uw_aggregate.py\n"
        )
        return 2

    data = json.loads(AGG_PATH.read_text(encoding="utf-8"))
    entries = list(data.get("entries") or [])

    # Detect cross-source-block hash conflicts for same (rom,quest,level,room_id).
    seen: dict[tuple, dict] = {}
    for e in entries:
        key = (e["rom"], e["quest"], e["level"], e["room_id"])
        h = hash_entry(e)
        if key in seen:
            prev = seen[key]
            if prev["_hash"] != h and prev["source_block"] != e["source_block"]:
                sys.stderr.write(
                    f"FATAL: conflicting hashes for {key} across source_blocks "
                    f"{prev['source_block']} vs {e['source_block']}\n"
                )
                return 3
        else:
            e2 = dict(e)
            e2["_hash"] = h
            seen[key] = e2

    deduped = list(seen.values())
    deduped.sort(key=lambda e: (
        e["map_id"], e["quest"], e["level"], e["source_block"], e["room_id"]
    ))

    counts = {0: 0, 1: 0}
    for e in deduped:
        counts[e["map_id"]] = counts.get(e["map_id"], 0) + 1
    print(f"orig (map_id=0): {counts[0]} entries")
    print(f"redux (map_id=1): {counts[1]} entries")

    emit_c(deduped, OUT_C)
    print(f"wrote {OUT_C} ({len(deduped)} total entries)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
