#!/usr/bin/env python3
"""synth_stairs_sfx.py — pre-render the NES Z1 cave "stairs" SFX to PCM.

The stairs descend sound is APU-NOISE-synthesized on NES (not a DMC sample), so
it is absent from the 7 extracted DMC samples (tools/extract_dmc_samples.py).
This reproduces it from the disassembly (RULE ZERO — periods/volumes/timing read
from reference/aldonunez/Z_00.asm:244 PlayStairsSfx, NOT by ear) and emits an
8-bit signed PCM in the same shape as data/audio/sfx_pcm.{c,h} so it can be
registered as SFX #8 (XGM PCM id 71) and played via audio_sfx_play(8).

NES driver (Z_00.asm:244 ContinueStairsSfx):
  EffectCounter = $38 (56 frames total, 1 frame = 1/60 s).
  $68 step counter: starts $0D, "one step lasts $C frames"; DEC each frame,
    reset to $0D at 0. Y = $68.
    Y >= 7        -> note byte $10 (period idx 0, volume 1)
    Y in 1..6     -> StairsSfxNotes[Y-1]
  note: NoisePeriod_400E = note & $0F ; NoiseVolume = (note>>4)|$10 (vol = note>>4)
  StairsSfxNotes = $0E,$0E,$4C,$6D,$8C,$CD.

NES noise channel: 15-bit LFSR, mode-0 feedback = bit0 XOR bit1, clocked every
NoisePeriodTable[idx] CPU cycles (NTSC). Channel outputs the volume when
(LFSR & 1) == 0, else 0. We render unipolar then DC-center to signed int8.

NOTE: the waveform is NOT byte-verifiable (no NES PCM reference exists) — it
ships on trigger + EffectRequest byte-parity + an ear check. The /octo:review
gate is for the synth math + the int8/rate/length output format.

Output: data/audio/sfx_pcm_stairs.{c,h}. Run from repo root:
  python tools/parity/cave_golden/synth_stairs_sfx.py
"""
from __future__ import annotations
from pathlib import Path

REPO = Path(__file__).resolve().parents[3]
OUT_C = REPO / "data" / "audio" / "sfx_pcm_stairs.c"
OUT_H = REPO / "data" / "audio" / "sfx_pcm_stairs.h"

# --- NES constants (NTSC) ---
CPU_HZ = 1789773.0
OUT_HZ = 14000          # matches SFX_PCM_RATE_HZ
FPS = 60.0
NOISE_PERIOD_NTSC = [4, 8, 16, 32, 64, 96, 128, 160,
                     202, 254, 380, 508, 762, 1016, 2034, 4068]
STAIRS_NOTES = [0x0E, 0x0E, 0x4C, 0x6D, 0x8C, 0xCD]
EFFECT_FRAMES = 0x38    # 56
STEP_RELOAD = 0x0D      # $68 start


def frame_note(frame_idx: int) -> int:
    """Reproduce the $68 step-counter note selection per played frame.
    Z_00.asm ContinueStairsSfx: $68 starts $0D(13); each frame DEC $68; Y=$68;
    when Y hits 0 it resets $68=$0D and IMMEDIATELY re-DECs to $0C in the SAME
    frame (BEQ :- -> LDA #$0D/STA $68 falls through to DEC) — so Y never plays 0,
    it steps 12,11,...,1,12,... a 12-frame period, no skip frame.
      Y in 7..12 -> note $10 (period idx 0, volume 1)
      Y in 1..6  -> StairsSfxNotes[Y-1]"""
    y = STEP_RELOAD - 1 - (frame_idx % (STEP_RELOAD - 1))   # 12,11,...,1,12,...
    if y >= 7:
        return 0x10
    return STAIRS_NOTES[y - 1]


def render() -> bytearray:
    total_samples = int(round(EFFECT_FRAMES / FPS * OUT_HZ))
    samples_per_frame = OUT_HZ / FPS
    apu_per_out = CPU_HZ / OUT_HZ
    lfsr = 1
    t_apu = 0.0          # APU cycles consumed by LFSR clocking
    raw = []             # unipolar 0..vol
    for s in range(total_samples):
        frame_idx = int(s / samples_per_frame)
        note = frame_note(frame_idx)   # always 1..12 valid (no skip frame)
        period = NOISE_PERIOD_NTSC[note & 0x0F]
        volume = note >> 4                 # 0..15
        target = s * apu_per_out
        # Advance the LFSR for the APU cycles elapsed since the last sample.
        while t_apu + period <= target:
            fb = (lfsr ^ (lfsr >> 1)) & 1  # mode-0: bit0 XOR bit1
            lfsr = ((lfsr >> 1) | (fb << 14)) & 0x7FFF
            t_apu += period
        out = volume if (lfsr & 1) == 0 else 0
        raw.append(out)
    # DC-center to signed int8: map unipolar [0..15] around 0, scale to ~+-100.
    pcm = bytearray()
    for v in raw:
        # v in 0..15 (mostly 0/1/vol). Center: (v - vol_mid) scaled.
        s8 = int(round((v / 15.0) * 100.0)) if v > 0 else 0
        if s8 > 127:
            s8 = 127
        if s8 < -128:
            s8 = -128
        pcm.append(s8 & 0xFF)
    # Pad to a 256-byte boundary (sfx_pcm convention).
    while len(pcm) % 256 != 0:
        pcm.append(0x00)
    return pcm


def emit(pcm: bytearray) -> None:
    # Match the data/audio/sfx_pcm.c format exactly: `const u8
    # __attribute__((aligned(256)))` holding signed values as unsigned bytes
    # (two's complement), so XGM_setPCM (expects u8*) and the sfx_pcm_entry_t
    # {id,data,len} shape line up with the DMC-generated bank.
    n = len(pcm)
    rows = []
    for i in range(0, n, 16):
        rows.append("    " + ", ".join(f"0x{b:02X}" for b in pcm[i:i+16]) + ",")
    body = "\n".join(rows)
    OUT_H.parent.mkdir(parents=True, exist_ok=True)
    OUT_H.write_text(
        "/* AUTO-GENERATED by tools/parity/cave_golden/synth_stairs_sfx.py */\n"
        "#ifndef SFX_PCM_STAIRS_H\n#define SFX_PCM_STAIRS_H\n"
        '#include "sfx_pcm.h"\n'
        "#define SFX_PCM_STAIRS_ID   71\n"
        f"#define SFX_PCM_STAIRS_LEN  {n}\n"
        "extern const u8 sfx_pcm_stairs[SFX_PCM_STAIRS_LEN];\n"
        "#endif\n", encoding="utf-8")
    OUT_C.write_text(
        "/* AUTO-GENERATED by tools/parity/cave_golden/synth_stairs_sfx.py.\n"
        " * NES Z1 stairs SFX (Z_00.asm:244) rendered via the NES noise LFSR.\n"
        " * 8-bit signed PCM (stored unsigned, 0x00-centered) @ 14000 Hz,\n"
        " * 256-byte padded — same shape as sfx_pcm.c (DMC bank). */\n"
        '#include "sfx_pcm_stairs.h"\n'
        "const u8 __attribute__((aligned(256))) sfx_pcm_stairs[SFX_PCM_STAIRS_LEN] = {\n"
        f"{body}\n}};\n", encoding="utf-8")
    print(f"wrote {OUT_C} + {OUT_H}  ({n} bytes, signed-in-u8 @ {OUT_HZ}Hz)")


if __name__ == "__main__":
    emit(render())
