"""Generate the NES item tile -> item atlas index table.

    python tools/atlas/gen_item_tile_atlas_idx.py

Output: src/game/enemies/item_tile_atlas_idx.h (checked in; freshness gate
entry "item_tile_atlas_idx" in tools/probes/check_generated_freshness.py).

The item atlas (RoomRom/src/atlas/items_chr_x4.c) is laid out by
RoomRom/tools/gen_atlas.py from RoomRom/data/item_chr_manifest.json: item_defs
in order, each NES tile emitted once (plus baked h-flip copies for mirrored
rules). This walks the same order (tools/probes/item_atlas_audit.py
replicates it byte-for-byte) and records, for every NES tile, the index of
its first unflipped copy. 0xFF = tile not in the atlas.

T-092: the previous hand-written table in enemy_render.c had drifted when the
atlas grew (42 of 76 entries pointed at other tiles; live NES CHR comparison).
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
MANIFEST = ROOT / "RoomRom" / "data" / "item_chr_manifest.json"
OUT = ROOT / "src" / "game" / "enemies" / "item_tile_atlas_idx.h"


def atlas_index_map(manifest: dict) -> tuple[dict[int, int], int]:
    idx: dict[int, int] = {}
    cur = 0
    for d in manifest["item_defs"]:
        rule = str(d.get("draw_rule", ""))
        tiles = [int(t, 16) for t in d["tile_ids"]]
        if "atlas_alias_note" in d:
            # tile_ids are atlas-local placeholders (fairy spark F0-F3, drop
            # heart E0/E1); the NES OAM tile that draws them is
            # nes_frame_tile. One narrow 8x16 frame per entry.
            if rule != "narrow_8x16" or len(tiles) != 2:
                raise SystemExit(f"{d['name']}: alias entries must be one narrow 8x16 frame")
            idx.setdefault(int(d["nes_frame_tile"], 16), cur)
            cur += 2
            continue
        if rule.startswith("wide_16x16_mirrored_8x16"):
            if len(tiles) % 2:
                raise SystemExit(f"{d['name']}: {rule} needs an even tile count")
            for i in range(0, len(tiles), 2):
                idx.setdefault(tiles[i], cur)
                idx.setdefault(tiles[i + 1], cur + 1)
                cur += 4                      # top, bottom, hflip(top), hflip(bottom)
        elif rule.startswith("mirrored_"):
            for t in tiles:
                idx.setdefault(t, cur)
                cur += 2                      # tile, hflip(tile)
        else:
            for t in tiles:
                idx.setdefault(t, cur)
                cur += 1
    return idx, cur


def main() -> int:
    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    idx, total = atlas_index_map(manifest)
    if total > 0xFF:
        raise SystemExit(f"atlas has {total} tiles; table entries are bytes")
    rows = []
    for base in range(0, 256, 16):
        cells = ", ".join(f"0x{idx.get(t, 0xFF):02X}" for t in range(base, base + 16))
        rows.append(f"    /* ${base:02X} */ {cells},")
    OUT.write_text(
        "/* Auto-generated by tools/atlas/gen_item_tile_atlas_idx.py - do not edit.\n"
        " * NES item tile id -> item atlas tile index (first unflipped copy),\n"
        " * from RoomRom/data/item_chr_manifest.json in gen_atlas.py order.\n"
        " * 0xFF = tile not in the atlas. */\n"
        "#ifndef ITEM_TILE_ATLAS_IDX_H\n"
        "#define ITEM_TILE_ATLAS_IDX_H\n\n"
        f"#define ITEM_TILE_ATLAS_TILE_COUNT {total}u\n\n"
        "static const unsigned char k_nes_item_tile_to_atlas_idx[256] = {\n"
        + "\n".join(rows) + "\n};\n\n#endif\n",
        encoding="utf-8")
    print(f"{OUT.relative_to(ROOT)}: {len(idx)} tiles mapped, atlas {total} tiles")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
