#!/usr/bin/env python3
"""gen_uw_collision_c.py — emit RoomRom/src/uw_collision_data.c from NES room data.

Generates two tables:
  uw_collision_grid[64][16][11]  — metatile class per unique_room_id
                                   (0=WALK, 1=WALL, 2=WATER, 3=HAZARD reserved)
  uw_lba_d[4][128]               — unique_room_id (& 0x3F) per (set,room_id)
                                   set 0 = levels 1-6 Q1 (LevelBlockUW1Q1)
                                   set 1 = levels 1-6 Q2 (LevelBlockUW1Q2)
                                   set 2 = levels 7-9 Q1 (LevelBlockUW2Q1)
                                   set 3 = levels 7-9 Q2 (LevelBlockUW2Q2)

Runtime lookup (header inlines):
  set = (level >= 7) ? 2 : 0;  if (quest == 2) set++;
  uid = uw_lba_d[set][room_id];
  cls = uw_collision_grid[uid][col][row];        // raw class
  walk = (cls == UW_CLASS_WALK);                 // bool

NES source:  reference/aldonunez/Z_05.asm:LayoutUWFloor
Output:      RoomRom/src/uw_collision_data.c
             RoomRom/src/uw_collision_data.h
"""

import re
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
DUNGEONS_C = REPO / "data" / "rooms" / "dungeons.c"
MANIFEST_JSON = REPO / "data" / "rooms" / "MANIFEST.json"
OUT_C = REPO / "RoomRom" / "src" / "uw_collision_data.c"
OUT_H = REPO / "RoomRom" / "src" / "uw_collision_data.h"

sys.path.insert(0, str(REPO / "tools" / "builder"))
from extract_uw_collision import (
    parse_dungeons_c, load_manifest, get_table, build_room_grid,
    GRID_COLS, GRID_ROWS,
)

NUM_UNIQUE_ROOMS = 64


def build_all_unique_grids(data: bytes, tables: dict) -> list:
    """Build grid for all 64 possible unique_room_ids."""
    grids = []
    for uid in range(NUM_UNIQUE_ROOMS):
        grid = build_room_grid(data, tables, uid)
        grids.append(grid)
    return grids


def build_lba_d_sets(data: bytes, tables: dict) -> list:
    """Return 4 × 128-byte LBA_D tables."""
    block_names = [
        "LevelBlockUW1Q1",  # set 0
        "LevelBlockUW1Q2",  # set 1
        "LevelBlockUW2Q1",  # set 2
        "LevelBlockUW2Q2",  # set 3
    ]
    result = []
    for bname in block_names:
        off, _ = tables[bname]
        d_table = [data[off + 0x180 + i] & 0x3F for i in range(128)]
        result.append(d_table)
    return result


def emit_c(grids: list, lba_d_sets: list) -> str:
    lines = [
        "/* uw_collision_data.c — auto-generated by tools/builder/gen_uw_collision_c.py",
        " * DO NOT EDIT. Regenerate with: python tools/builder/gen_uw_collision_c.py",
        " *",
        " * NES source: reference/aldonunez/Z_05.asm:LayoutUWFloor",
        " * 64 unique room layouts x 16 cols x 11 rows.",
        " * Cell value = UW_CLASS_* enum (0=WALK, 1=WALL, 2=WATER, 3=HAZARD).",
        " */",
        "#include \"uw_collision_data.h\"",
        "",
        "/* [unique_room_id][col][row] */",
        "const unsigned char uw_collision_grid[64][16][11] = {",
    ]
    for uid, grid in enumerate(grids):
        lines.append(f"    /* uid={uid} */")
        lines.append("    {")
        for col in range(GRID_COLS):
            row_vals = ", ".join(str(grid[col][row]) for row in range(GRID_ROWS))
            lines.append(f"        {{ {row_vals} }},")
        lines.append("    },")
    lines.append("};")
    lines.append("")
    lines.append("/* [set][room_id]: set 0=L1-6Q1, 1=L1-6Q2, 2=L7-9Q1, 3=L7-9Q2 */")
    lines.append("const unsigned char uw_lba_d[4][128] = {")
    set_names = ["L1-6Q1", "L1-6Q2", "L7-9Q1", "L7-9Q2"]
    for si, (d_table, sname) in enumerate(zip(lba_d_sets, set_names)):
        lines.append(f"    /* set {si} = {sname} */")
        lines.append("    {")
        for chunk_start in range(0, 128, 16):
            chunk = d_table[chunk_start : chunk_start + 16]
            lines.append("        " + ", ".join(str(v) for v in chunk) + ",")
        lines.append("    },")
    lines.append("};")
    return "\n".join(lines) + "\n"


def emit_h() -> str:
    return """\
/* uw_collision_data.h — auto-generated by tools/builder/gen_uw_collision_c.py */
/* DO NOT EDIT. */
#ifndef UW_COLLISION_DATA_H
#define UW_COLLISION_DATA_H

/* 2-bit metatile classification per debate ph5-t52-precheck Q3 (Option B).
 * Byte-per-cell storage (only low 2 bits used; upper 6 bits zero). */
#define UW_CLASS_WALK    0u
#define UW_CLASS_WALL    1u
#define UW_CLASS_WATER   2u
#define UW_CLASS_HAZARD  3u   /* reserved for 5.3 hazard floor work */

/* [unique_room_id][col][row] metatile class (UW_CLASS_*).
 * col 0..15, row 0..10 in metatile coords. Border cells = UW_CLASS_WALL. */
extern const unsigned char uw_collision_grid[64][16][11];

/* [set][room_id] unique_room_id (0..63).
 * set: 0=levels1-6 Q1, 1=levels1-6 Q2, 2=levels7-9 Q1, 3=levels7-9 Q2 */
extern const unsigned char uw_lba_d[4][128];

/* Return the LBA_D set index for a given level (1-9) and quest (1-2). */
static inline unsigned char uw_lba_d_set(unsigned char level, unsigned char quest)
{
    unsigned char base = (level >= 7) ? 2u : 0u;
    return (unsigned char)(base + (quest == 2u ? 1u : 0u));
}

/* Raw metatile class (UW_CLASS_*) at (col, row) in the given room.
 * Use this for 5.3+ semantics (water/hazard/stair logic). */
static inline unsigned char uw_room_metatile_class(
    unsigned char level, unsigned char quest,
    unsigned char room_id, unsigned char col, unsigned char row)
{
    unsigned char set = uw_lba_d_set(level, quest);
    unsigned char uid = uw_lba_d[set][room_id];
    return uw_collision_grid[uid][col][row];
}

/* Walkable test: 1 if class == WALK. WATER/WALL/HAZARD all block Link by
 * default; raft/conditional walkability is runtime game state, not stored
 * in this table. */
static inline unsigned char uw_room_walkable(
    unsigned char level, unsigned char quest,
    unsigned char room_id, unsigned char col, unsigned char row)
{
    return (unsigned char)(uw_room_metatile_class(level, quest, room_id,
                                                  col, row) == UW_CLASS_WALK);
}

#endif /* UW_COLLISION_DATA_H */
"""


def main() -> int:
    print("gen_uw_collision_c.py")
    data = parse_dungeons_c(DUNGEONS_C)
    tables, _sha = load_manifest(MANIFEST_JSON)

    grids = build_all_unique_grids(data, tables)
    lba_d_sets = build_lba_d_sets(data, tables)

    c_text = emit_c(grids, lba_d_sets)
    h_text = emit_h()

    OUT_C.write_text(c_text, encoding="utf-8")
    OUT_H.write_text(h_text, encoding="utf-8")
    print(f"  Wrote {OUT_C.relative_to(REPO)}")
    print(f"  Wrote {OUT_H.relative_to(REPO)}")
    print(f"  Grid: {NUM_UNIQUE_ROOMS} unique rooms x {GRID_COLS} cols x {GRID_ROWS} rows = "
          f"{NUM_UNIQUE_ROOMS * GRID_COLS * GRID_ROWS} bytes")
    print("OK")
    return 0


if __name__ == "__main__":
    sys.exit(main())
