"""Your own VGMs in your own build (local only; nothing is shipped or uploaded).

Converts every .vgm in a folder with SGDK's xgmtool and writes
build/local_music/local_music.c: one XGM blob per file plus a table from NES
song request to blob. src/sgdk_adapter/audio_adapter.c plays a song from
that table when the build defines ZELDA_LOCAL_MUSIC (build_debug.py does
when ZELDA_LOCAL_MUSIC_C points at the file). Songs without a file keep the
port's own music.

Files are matched to NES songs by name (case-insensitive):
    title / intro                -> $80 title
    overworld                    -> $01 overworld
    underworld / dungeon         -> $40 dungeons 1-8
    level9 / level 9 / lastlevel -> $20 level 9
    ganon                        -> $02 Ganon
    triforce / endlevel          -> $04 level cleared (Triforce piece)
    zelda                        -> $06 Zelda rescued
    item                         -> $08 item get
    ending / credits             -> $10 ending

    python tools/builder/local_music.py <folder>
Exit: 0 written; 1 no usable file or a conversion failed.
"""
from __future__ import annotations

import os
import re
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUT_C = ROOT / "build" / "local_music" / "local_music.c"
XGMTOOL = ROOT / "sgdk" / "bin" / "xgmtool.exe"

# (song request, label, name patterns); first match wins, most specific first.
SONGS = (
    (0x20, "level 9", r"level\s*_?9|last\s*_?level"),
    (0x02, "Ganon", r"ganon"),
    (0x04, "level cleared", r"triforce|end\s*_?level"),
    (0x06, "Zelda rescued", r"zelda"),
    (0x08, "item get", r"item"),
    (0x10, "ending", r"ending|credits"),
    (0x80, "title", r"title|intro"),
    (0x40, "dungeon", r"underworld|dungeon"),
    (0x01, "overworld", r"overworld"),
)


def song_for(name: str) -> tuple[int, str] | None:
    stem = Path(name).stem.lower()
    for song, label, pat in SONGS:
        if re.search(pat, stem):
            return song, label
    return None


def xgm_compile(vgm: Path, out: Path) -> None:
    argv = [str(XGMTOOL), str(vgm), str(out), "-n", "-s"]
    if os.name != "nt":
        argv = ["wine"] + argv
    env = dict(os.environ, WINEDEBUG="-all")
    r = subprocess.run(argv, capture_output=True, text=True, env=env)
    if r.returncode or not out.is_file():
        raise SystemExit(f"ERROR: xgmtool failed on {vgm.name}: {(r.stdout + r.stderr).strip()[-400:]}")


def main() -> int:
    if len(sys.argv) != 2:
        print(__doc__, file=sys.stderr)
        return 1
    folder = Path(sys.argv[1])
    vgms = sorted(p for p in folder.glob("*") if p.suffix.lower() in (".vgm", ".vgz"))
    picked: dict[int, tuple[str, Path]] = {}
    for p in vgms:
        m = song_for(p.name)
        if m is None:
            print(f"  skipped {p.name}: name matches no song")
            continue
        song, label = m
        if song in picked:
            print(f"  skipped {p.name}: {label} already taken by {picked[song][1].name}")
            continue
        picked[song] = (label, p)
    if not picked:
        print(f"ERROR: no usable .vgm in {folder}", file=sys.stderr)
        return 1
    lines = ["/* Generated by tools/builder/local_music.py from your own VGMs. Local build only. */",
             "#include \"local_music.h\"", ""]
    rows = []
    with tempfile.TemporaryDirectory() as td:
        for song, (label, p) in sorted(picked.items()):
            out = Path(td) / f"song_{song:02x}.bin"
            xgm_compile(p, out)
            data = out.read_bytes()
            sym = f"local_song_{song:02x}"
            lines.append(f"/* ${song:02X} {label}: {p.name} ({len(data)} bytes) */")
            lines.append(f"static const unsigned char __attribute__((aligned(256))) {sym}[{len(data)}] = {{")
            for i in range(0, len(data), 16):
                lines.append("    " + ", ".join(f"0x{b:02x}" for b in data[i:i + 16]) + ",")
            lines.append("};")
            rows.append(f"    {{ 0x{song:02x}u, {sym} }},")
            print(f"  ${song:02X} {label:14s} <- {p.name} ({len(data)} bytes)")
    lines += ["", "const local_song_t local_music[] = {", *rows, "};",
              f"const unsigned char local_music_count = {len(rows)}u;", ""]
    OUT_C.parent.mkdir(parents=True, exist_ok=True)
    OUT_C.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    (OUT_C.parent / "local_music.h").write_text(
        "#ifndef LOCAL_MUSIC_H\n#define LOCAL_MUSIC_H\n"
        "typedef struct { unsigned char song; const unsigned char *xgm; } local_song_t;\n"
        "extern const local_song_t local_music[];\nextern const unsigned char local_music_count;\n"
        "#endif\n", encoding="utf-8", newline="\n")
    print(f"wrote {OUT_C.relative_to(ROOT)} ({len(rows)} songs)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
