"""Release package contents = the files a full conversion actually reads.

Unpacks a broad candidate package (every tracked, non-game-derived file
under make_package.CANDIDATES) into a clean directory, runs one full
conversion there under strace, and keeps every candidate file that any
process (Python, the extractors, the SGDK toolchain under Wine) opened for
reading or executed. Result: tools/builder/package_manifest.txt, which
make_package.py packages (plus make_package.ALWAYS and sgdk/).

    python tools/builder/package_closure.py --rom <zelda.nes> --redux-patch <redux .ips/.zip>
        [--check]   compare with the committed manifest instead of writing it
    python tools/builder/package_closure.py --from-trace <strace.log>... --tree <unpacked root>
        derive from existing traces of runs in that tree (no build)
Linux only (strace; the toolchain runs under Wine there).
Exit: 0 written / matches; 1 bad input; 2 conversion failed; 3 manifest differs.
"""
from __future__ import annotations

import argparse
import os
import re
import shutil
import subprocess
import sys
import tempfile
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "tools" / "builder"))
import make_package  # noqa: E402

MANIFEST = ROOT / "tools" / "builder" / "package_manifest.txt"
CALL = re.compile(r'(openat|execve)\((?:AT_FDCWD, )?"((?:[^"\\]|\\.)*)"(?:, ([A-Z_|]+))?')
WRITE_FLAGS = ("O_WRONLY", "O_TRUNC", "O_CREAT")
WINE_DRIVE = re.compile(r"^.*/dosdevices/z:(?=/)", re.I)


def read_paths(trace: Path, tree: Path) -> set[str]:
    """Package-relative paths opened for reading or executed."""
    out = set()
    tree = tree.resolve()
    for line in trace.open(encoding="utf-8", errors="replace"):
        m = CALL.search(line)
        if not m or "ENOENT" in line or "ENOTDIR" in line:
            continue
        call, path, flags = m.groups()
        if call == "openat" and flags and (any(f in flags for f in WRITE_FLAGS)
                                           or "O_DIRECTORY" in flags):
            continue
        path = path.encode().decode("unicode_escape").encode("latin-1").decode("utf-8")
        # Wine opens host files through its drive links: <prefix>/dosdevices/z:/<unix path>.
        path = WINE_DRIVE.sub("", path)
        p = Path(path)
        if not p.is_absolute():
            p = tree / p          # build.py runs every step with cwd = package root
        try:
            rel = Path(os.path.normpath(p)).relative_to(tree).as_posix()
        except ValueError:
            continue
        out.add(rel)
    return out


def compiler_inputs(tree: Path) -> set[str]:
    """GCC's actual source/header reads, including Wine's server-side opens.

    Wine can delegate opens to an already-running server outside strace's
    process tree. Successful objects' -MMD files retain those dependencies.
    A fresh conversion's tree, not a developer checkout, supplies these.
    """
    tree = tree.resolve()
    found = set()
    for dep in (tree / "build/debug_project/out").glob("*.d"):
        if not dep.with_suffix(".o").is_file():
            continue
        text = dep.read_text(encoding="utf-8").replace("\\\n", " ")
        tokens = [s.replace("\\ ", " ") for s in re.findall(r"(?:\\ |\S)+", text)]
        split = next((i for i, s in enumerate(tokens) if s.endswith(":")), None)
        if split is None:
            raise ValueError(f"malformed compiler dependency file: {dep.name}")
        for s in tokens[split + 1:]:
            s = re.sub(r"(?i)^z:(?=/)", "", s)
            path = Path(s)
            if not path.is_absolute():
                path = tree / path
            try:
                found.add(Path(os.path.normpath(path)).relative_to(tree).as_posix())
            except ValueError:
                pass
    return found


def closure(traces: list[Path], tree: Path, candidates: list[str]) -> list[str]:
    opened = compiler_inputs(tree) | set().union(*(read_paths(t, tree) for t in traces))
    keep = [c for c in candidates
            if c in opened and not c.startswith(make_package.THIRD_PARTY)
            and c not in make_package.ALWAYS]
    return sorted(keep)


def write_manifest(files: list[str], path: Path) -> None:
    path.write_text("# Generated by tools/builder/package_closure.py: files a full conversion\n"
                    "# reads. make_package.py ships these + make_package.ALWAYS + sgdk/.\n"
                    + "".join(f"{f}\n" for f in files), encoding="utf-8", newline="\n")


def traced_build(rom: Path, redux: Path, base: Path) -> tuple[Path, Path, list[str]]:
    candidates = make_package.candidate_files()
    pkg = base / "candidates.zip"
    make_package.write_zip(candidates, pkg)
    with zipfile.ZipFile(pkg) as z:
        z.extractall(base / "clean tree")
    tree = base / "clean tree" / make_package.PACKAGE_ROOT
    trace = base / "strace.log"
    argv = ["strace", "-f", "-qq", "-e", "trace=openat,execve", "-e", "signal=none",
            "-o", str(trace), sys.executable, str(tree / "tools" / "builder" / "build.py"),
            str(rom), "--redux-patch", str(redux), "--output", str(base / "out" / "Zelda.md")]
    log = base / "convert.log"
    with open(log, "w", encoding="utf-8") as f:
        r = subprocess.run(argv, cwd=tree, stdout=f, stderr=subprocess.STDOUT, check=False)
    if r.returncode:
        print(log.read_text(encoding="utf-8", errors="replace")[-3000:], file=sys.stderr)
        raise SystemExit(2)
    return trace, tree, candidates


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--rom", type=Path)
    ap.add_argument("--redux-patch", type=Path)
    ap.add_argument("--from-trace", type=Path, nargs="+")
    ap.add_argument("--tree", type=Path)
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    base = Path(tempfile.mkdtemp(prefix="package closure "))
    try:
        if args.from_trace:
            if not args.tree:
                ap.error("--from-trace needs --tree")
            traces, tree, candidates = args.from_trace, args.tree, make_package.candidate_files()
        else:
            if not (args.rom and args.redux_patch and args.rom.is_file()
                    and args.redux_patch.is_file()):
                print("ERROR: --rom and --redux-patch files are required", file=sys.stderr)
                return 1
            if not shutil.which("strace"):
                print("ERROR: strace not found", file=sys.stderr)
                return 1
            trace, tree, candidates = traced_build(args.rom, args.redux_patch, base)
            traces = [trace]
        files = closure(traces, tree, candidates)
        if args.check:
            committed = make_package.manifest_files()
            if committed != files:
                extra = sorted(set(files) - set(committed))
                gone = sorted(set(committed) - set(files))
                print(f"package_closure: FAIL - manifest differs: +{len(extra)} {extra[:10]} "
                      f"-{len(gone)} {gone[:10]}", file=sys.stderr)
                return 3
            print(f"package_closure: PASS - {len(files)} files, manifest reproduces")
            return 0
        write_manifest(files, MANIFEST)
        print(f"wrote {MANIFEST.relative_to(ROOT)} ({len(files)} of {len(candidates)} "
              "candidate files)")
        return 0
    finally:
        shutil.rmtree(base, ignore_errors=True)


if __name__ == "__main__":
    sys.exit(main())
