"""Extract Zelda intro assets from the committed disassembly reference tree.

Reads reference/aldonunez/dat/ and emits src/gen/intro_*.c files containing
font CHR, art CHR, palette table, story tilemap, showcase tilemap, restore
blobs, and a handoff-state struct. Also emits src/gen/intro_asset_hashes.txt
listing SHA256 of every output for regression detection.

Task 5 additions: common_bg_chr, sprite_chr, misc_chr, punct_chr (static
copy), blink_chr, combined_palette, treasures_tilemap. Story tilemap is
now re-emitted using the GameCube-version composition from
tools/intro_demo/compose_story_tilemap.py.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent

# Canonical NES palette RGB values (Nesdev "2C02" LUT, first 64 entries).
# Each entry is (R, G, B) in 0..255.
NES_PALETTE_RGB = [
    (0x62, 0x62, 0x62), (0x00, 0x1F, 0xB2), (0x24, 0x04, 0xC8), (0x52, 0x00, 0xB2),
    (0x73, 0x00, 0x76), (0x80, 0x00, 0x24), (0x73, 0x0B, 0x00), (0x52, 0x28, 0x00),
    (0x24, 0x44, 0x00), (0x00, 0x57, 0x00), (0x00, 0x5C, 0x00), (0x00, 0x53, 0x24),
    (0x00, 0x3C, 0x76), (0x00, 0x00, 0x00), (0x00, 0x00, 0x00), (0x00, 0x00, 0x00),

    (0xAB, 0xAB, 0xAB), (0x0D, 0x57, 0xFF), (0x4B, 0x30, 0xFF), (0x8A, 0x13, 0xFF),
    (0xBC, 0x08, 0xD6), (0xD2, 0x12, 0x69), (0xC7, 0x2E, 0x00), (0x9D, 0x54, 0x00),
    (0x60, 0x7B, 0x00), (0x20, 0x98, 0x00), (0x00, 0xA3, 0x00), (0x00, 0x99, 0x42),
    (0x00, 0x7D, 0xB4), (0x00, 0x00, 0x00), (0x00, 0x00, 0x00), (0x00, 0x00, 0x00),

    (0xFF, 0xFF, 0xFF), (0x53, 0xAE, 0xFF), (0x90, 0x85, 0xFF), (0xD3, 0x65, 0xFF),
    (0xFF, 0x57, 0xFF), (0xFF, 0x5D, 0xCF), (0xFF, 0x77, 0x57), (0xFA, 0x9E, 0x00),
    (0xBD, 0xC7, 0x00), (0x7A, 0xE7, 0x00), (0x43, 0xF6, 0x11), (0x26, 0xEF, 0x7E),
    (0x2C, 0xD5, 0xF6), (0x4E, 0x4E, 0x4E), (0x00, 0x00, 0x00), (0x00, 0x00, 0x00),

    (0xFF, 0xFF, 0xFF), (0xB6, 0xE1, 0xFF), (0xCE, 0xD1, 0xFF), (0xE9, 0xC3, 0xFF),
    (0xFF, 0xBC, 0xFF), (0xFF, 0xBD, 0xF4), (0xFF, 0xC6, 0xC3), (0xFF, 0xD5, 0x9A),
    (0xE9, 0xE6, 0x81), (0xCE, 0xF4, 0x81), (0xB6, 0xFB, 0x9A), (0xA9, 0xFA, 0xC3),
    (0xA9, 0xF0, 0xF4), (0xB8, 0xB8, 0xB8), (0x00, 0x00, 0x00), (0x00, 0x00, 0x00),
]

def _quantize_channel(v: int) -> int:
    """Quantize an 8-bit channel to the Genesis 3-bit palette step (0/2/4/.../14)."""
    # Map [0..255] -> one of 0, 2, 4, 6, 8, 10, 12, 14 (8 discrete steps).
    step = min(7, v * 8 // 256)
    return step * 2

def nes_color_to_gen_cram(nes_idx: int) -> int:
    """Convert NES palette byte index (0..63) to a Genesis CRAM word.

    Genesis CRAM word format: 0000 BBB0 GGG0 RRR0 (little-endian bits).
    """
    if not 0 <= nes_idx < 64:
        raise ValueError(f"nes palette index out of range: {nes_idx}")
    r, g, b = NES_PALETTE_RGB[nes_idx]
    return (_quantize_channel(b) << 8) | (_quantize_channel(g) << 4) | _quantize_channel(r)

def nes_tile_to_gen_tile(nes: bytes, color_shift: int = 0) -> bytes:
    """Convert a single 8x8 NES 2bpp tile (16 bytes) to Genesis 4bpp (32 bytes).

    NES layout: 8 bytes of bitplane 0 (rows 0..7), then 8 bytes of bitplane 1.
    Genesis layout: 8 rows x 4 bytes/row; each row packs 8 pixels as 4-bit
    indices, high nibble first.

    color_shift: add to non-zero color values so tile references higher Genesis
    palette slots. Sprite tiles use shift=4 to read slots 4-7 (NES sprite
    palette) instead of 0-3 (background palette).
    """
    if len(nes) != 16:
        raise ValueError(f"nes tile must be 16 bytes, got {len(nes)}")
    out = bytearray(32)
    for row in range(8):
        bp0 = nes[row]
        bp1 = nes[row + 8]
        row_out = bytearray(4)
        for px in range(8):
            bit = 7 - px
            color = ((bp0 >> bit) & 1) | (((bp1 >> bit) & 1) << 1)
            if color != 0 and color_shift != 0:
                color = (color + color_shift) & 0x0F
            byte_idx = px >> 1
            if (px & 1) == 0:
                row_out[byte_idx] |= (color & 0x0F) << 4
            else:
                row_out[byte_idx] |= (color & 0x0F)
        out[row * 4:(row + 1) * 4] = row_out
    return bytes(out)

# Story palette record lives in src/frontend_runtime.c. Duplicate the values
# here rather than parsing C - the record is stable and small.
STORY_PALETTE_RECORD = [
    0x3F, 0x00, 0x20, 0x0F, 0x30, 0x30, 0x30, 0x0F, 0x21, 0x30, 0x30, 0x0F,
    0x16, 0x30, 0x30, 0x0F, 0x29, 0x1A, 0x09, 0x0F, 0x29, 0x37, 0x17, 0x0F,
    0x02, 0x22, 0x30, 0x0F, 0x16, 0x27, 0x30, 0x0F, 0x0B, 0x1B, 0x2B, 0xFF,
]

def _emit_chr_array(out_path: Path, symbol: str, data: bytes) -> None:
    """Emit a C array of unsigned chars to a file."""
    lines = [f"/* Auto-generated by tools/extract_intro_assets.py - do not edit. */\n",
             f"const unsigned char {symbol}[{len(data)}] = {{\n"]
    for i in range(0, len(data), 16):
        row = ", ".join(f"0x{b:02X}" for b in data[i:i+16])
        lines.append(f"    {row},\n")
    lines.append("};\n")
    lines.append(f"const unsigned long {symbol}_size = {len(data)};\n")
    out_path.write_text("".join(lines), encoding="utf-8", newline="\n")

def _build_story_cram() -> list[int]:
    """Convert the NES story palette record to a 64-entry Genesis CRAM buffer."""
    # Record layout (NES-style PPU transfer): skip 3-byte header, then 32 NES
    # palette bytes (4 sub-palettes x 8 entries, of which 0..3 are meaningful
    # per sub-palette in NES; Genesis uses 4 palettes x 16 colors).
    nes_bytes = STORY_PALETTE_RECORD[3:3 + 32]
    cram = [0] * 64
    for subpal in range(4):
        for color in range(4):
            nes_idx = nes_bytes[subpal * 4 + color] & 0x3F
            cram[subpal * 16 + color] = nes_color_to_gen_cram(nes_idx)
    return cram

def _emit_palette(out_path: Path, cram: list[int]) -> None:
    lines = [f"/* Auto-generated by tools/extract_intro_assets.py - do not edit. */\n",
             f"const unsigned short intro_palette[64] = {{\n"]
    for i in range(0, 64, 8):
        row = ", ".join(f"0x{v:04X}" for v in cram[i:i+8])
        lines.append(f"    {row},\n")
    lines.append("};\n")
    out_path.write_text("".join(lines), encoding="utf-8", newline="\n")

def _load_nes_chr(path: Path) -> bytes:
    """Read NES 2bpp CHR blob, convert to Genesis 4bpp, return concatenated bytes."""
    nes = path.read_bytes()
    assert len(nes) % 16 == 0, f"{path}: CHR length not multiple of 16"
    gen = bytearray()
    for i in range(0, len(nes), 16):
        gen += nes_tile_to_gen_tile(nes[i:i+16])
    return bytes(gen)

def _parse_ppu_transfer_records(data: bytes) -> list[tuple[int, bytes]]:
    """Parse a stream of NES PPU transfer records (addr_hi, addr_lo, count, data[count]).

    Trailing $FF byte (or any byte that can't start a valid record) terminates.
    Returns [(addr, payload), ...].
    """
    out: list[tuple[int, bytes]] = []
    i = 0
    while i + 3 <= len(data):
        hi = data[i]
        if hi == 0xFF:
            break
        lo = data[i+1]
        n = data[i+2]
        if i + 3 + n > len(data):
            break
        out.append(((hi << 8) | lo, bytes(data[i+3:i+3+n])))
        i += 3 + n
    return out

def _build_nt1_tilemap(raw: bytes) -> tuple[list[int], int]:
    """Parse an NES PPU transfer record stream that fills NT1 + its attribute
    table, fold the attribute bits into per-cell palette indices, and return
    Genesis nametable words.

    Each NES attribute byte covers a 4x4 tile quad; bits 1:0 = top-left 2x2
    palette, 3:2 = top-right, 5:4 = bottom-left, 7:6 = bottom-right.
    Genesis cell word: (palette << 13) | tile_idx.

    Records targeting NT2 ($2800+) are ignored — they describe rows only the
    NES runtime composer reaches, and the native rewrite handles scroll past
    row 29 separately.
    """
    records = _parse_ppu_transfer_records(raw)

    ROWS = 30
    COLS = 32
    tiles = [0] * (ROWS * COLS)
    attrs = [0] * 64  # NT1 attribute table is 64 bytes

    for addr, payload in records:
        if 0x2000 <= addr < 0x23C0:
            off = addr - 0x2000
            for k, b in enumerate(payload):
                idx = off + k
                if idx < len(tiles):
                    tiles[idx] = b
        elif 0x23C0 <= addr < 0x2400:
            off = addr - 0x23C0
            for k, b in enumerate(payload):
                if off + k < len(attrs):
                    attrs[off + k] = b
        # Records into NT2 ($2800+) describe rows that only become visible
        # via runtime composition on the NES; the native rewrite handles
        # scroll past row 29 separately and ignores them here.

    def _pal_for_cell(r: int, c: int) -> int:
        attr_idx = (r // 4) * 8 + (c // 4)
        quad_row = (r >> 1) & 1
        quad_col = (c >> 1) & 1
        shift = (quad_row * 2 + quad_col) * 2
        return (attrs[attr_idx] >> shift) & 3

    cells = [0] * (ROWS * COLS)
    for r in range(ROWS):
        for c in range(COLS):
            tile = tiles[r * COLS + c]
            pal = _pal_for_cell(r, c)
            cells[r * COLS + c] = ((pal & 3) << 13) | (tile & 0x7FF)
    return cells, ROWS

def _build_story_tilemap(ref_dir: Path) -> tuple[list[int], int]:
    raw = (ref_dir / "StoryTileAttrTransferBuf.dat").read_bytes()
    return _build_nt1_tilemap(raw)

def _build_showcase_tilemap(ref_dir: Path) -> tuple[list[int], int]:
    raw = (ref_dir / "GameTitleTransferBuf.dat").read_bytes()
    return _build_nt1_tilemap(raw)

def _emit_handoff_state(out_path: Path, json_path: Path) -> None:
    """Emit INTRO_HANDOFF_EXPECTED struct from the captured handoff state JSON.

    The capture JSON has the shape {field: {"addr": "0x...", "value": "0x.."}}
    plus metadata keys (capture_frame, mode_at_capture, submode_at_capture)
    that describe when the snapshot was taken. The metadata keys are skipped;
    only byte fields with an addr+value pair become struct initializers.
    """
    data = json.loads(json_path.read_text())
    lines = [f"/* Auto-generated by tools/extract_intro_assets.py - do not edit. */\n",
             f'#include "intro_handoff.h"\n\n',
             "const intro_handoff_state_t INTRO_HANDOFF_EXPECTED = {\n"]
    for k, v in data.items():
        if not isinstance(v, dict) or "value" not in v:
            continue
        byte = int(v["value"], 16) & 0xFF
        lines.append(f"    .{k} = 0x{byte:02X},\n")
    lines.append("};\n")
    out_path.write_text("".join(lines), encoding="utf-8", newline="\n")

def _emit_tilemap(out_path: Path, symbol: str, cells: list[int], rows: int) -> None:
    lines = [f"/* Auto-generated by tools/extract_intro_assets.py - do not edit. */\n",
             f"const unsigned short {symbol}_rows = {rows};\n",
             f"const unsigned short {symbol}[{rows * 32}] = {{\n"]
    for r in range(rows):
        row = ", ".join(f"0x{c:04X}" for c in cells[r*32:(r+1)*32])
        lines.append(f"    {row},\n")
    lines.append("};\n")
    out_path.write_text("".join(lines), encoding="utf-8", newline="\n")

# ---------------------------------------------------------------------------
# Title-screen asset helpers
# ---------------------------------------------------------------------------


def _read_title_bg_chr() -> bytes:
    """Concatenate CommonBackgroundPatterns + DemoBackgroundPatterns +
    CommonMiscPatterns and convert to Genesis 4bpp (color_shift=0)."""
    ref_dir = REPO / "reference" / "aldonunez" / "dat"
    common = (ref_dir / "CommonBackgroundPatterns.dat").read_bytes()
    demo   = (ref_dir / "DemoBackgroundPatterns.dat").read_bytes()
    misc   = (ref_dir / "CommonMiscPatterns.dat").read_bytes()
    bg_data = common + demo + misc
    n_tiles = len(bg_data) // 16
    gen = bytearray()
    for t in range(n_tiles):
        gen += nes_tile_to_gen_tile(bg_data[t*16:(t+1)*16], color_shift=0)
    return bytes(gen)

def _read_title_sprite_chr() -> bytes:
    """NES sprite pattern table 0 at the title ($0000-$0FFF, 256 tiles):
    CommonSpritePatterns (112 tiles) then DemoSpritePatterns (144), as the
    game uploads them. Converted to Genesis 4bpp with color_shift=4.
    (Equal to the title-frame CHR capture tools/intro_demo/nes_full/
    chr_title.bin, which this replaced.)"""
    ref_dir = REPO / "reference" / "aldonunez" / "dat"
    sprite_chr = ((ref_dir / "CommonSpritePatterns.dat").read_bytes() +
                  (ref_dir / "DemoSpritePatterns.dat").read_bytes())
    if len(sprite_chr) != 0x1000:
        raise ValueError(f"sprite pattern table must be 4096 bytes, got {len(sprite_chr)}")
    n_tiles = len(sprite_chr) // 16
    gen = bytearray()
    for t in range(n_tiles):
        gen += nes_tile_to_gen_tile(sprite_chr[t*16:(t+1)*16], color_shift=4)
    return bytes(gen)

def _nes_palram_after_record(record: list[int]) -> list[int]:
    """NES PALRAM after a 32-byte $3F00 transfer record, as BizHawk's PALRAM
    domain shows it: $3F10/$3F14/$3F18/$3F1C are mirrors, so the record's
    sprite color-0 writes land in $3F00/$3F04/$3F08/$3F0C (written last)
    and the mirror cells read 0."""
    if record[:3] != [0x3F, 0x00, 0x20] or len(record) < 35:
        raise ValueError("expected a 32-byte $3F00 palette transfer record")
    pal = list(record[3:35])
    for k in range(4):
        pal[k * 4] = pal[16 + k * 4]
        pal[16 + k * 4] = 0
    return pal

# Z_02.asm:429 TitlePaletteTransferRecord.
TITLE_PALETTE_RECORD = [
    0x3F, 0x00, 0x20, 0x36, 0x0F, 0x00, 0x10, 0x36, 0x17, 0x27, 0x0F, 0x36,
    0x08, 0x1A, 0x28, 0x36, 0x30, 0x3B, 0x22, 0x36, 0x30, 0x3B, 0x16, 0x36,
    0x17, 0x27, 0x0F, 0x36, 0x08, 0x1A, 0x28, 0x36, 0x30, 0x3B, 0x22, 0xFF,
]
# Title PALRAM is taken at Triforce-glow phase 1: Z_02.asm:947
# TriforceGlowingColors[1] = $37 replaces $3F06 (TriforcePaletteTransferRecord
# writes $3F04-$3F07).
TITLE_GLOW_PHASE = 1
TRIFORCE_GLOWING_COLORS = [0x27, 0x37, 0x37, 0x27, 0x17, 0x07, 0x07, 0x17]

def _title_palram() -> list[int]:
    pal = _nes_palram_after_record(TITLE_PALETTE_RECORD)
    pal[6] = TRIFORCE_GLOWING_COLORS[TITLE_GLOW_PHASE]
    return pal

def _read_title_palette() -> list[int]:
    """NES PALRAM at the title (TitlePaletteTransferRecord, glow phase 1;
    equal to the title capture tools/intro_demo/nes_full/palram_title.bin
    this replaced), packed into the 64-word Genesis CRAM combined layout:
      Gen pal P slots 0-3  = NES BG pal P  (PALRAM $3F00 + P*4)
      Gen pal P slots 4-7  = NES SPR pal P  (PALRAM $3F10 + P*4)
      Gen pal P slots 8-15 = 0 (unused)"""
    pal = _title_palram()
    cram = [0] * 64
    for p in range(4):
        for c in range(4):
            cram[p*16 + c]     = nes_color_to_gen_cram(pal[p*4 + c])
            cram[p*16 + 4 + c] = nes_color_to_gen_cram(pal[16 + p*4 + c])
    return cram

def _emit_title_palette(out_path: Path, cram: list[int]) -> None:
    """Emit intro_title_palette[64] as a C array."""
    lines = [
        "/* Auto-generated by tools/extract_intro_assets.py - do not edit. */\n",
        "const unsigned short intro_title_palette[64] = {\n",
    ]
    for i in range(0, 64, 8):
        lines.append("    " + ", ".join(f"0x{w:04X}" for w in cram[i:i+8]) + ",\n")
    lines.append("};\n")
    out_path.write_text("".join(lines), encoding="utf-8", newline="\n")

def _build_title_tilemap(ref_dir: Path) -> tuple[list[int], int]:
    """Title tilemap uses the same source data and layout as the showcase tilemap."""
    return _build_showcase_tilemap(ref_dir)

def _emit_title_tilemap(out_path: Path, cells: list[int], rows: int) -> None:
    lines = [
        "/* Auto-generated by tools/extract_intro_assets.py - do not edit. */\n",
        f"const unsigned short intro_title_tilemap_rows = {rows};\n",
        f"const unsigned short intro_title_tilemap[{rows * 32}] = {{\n",
    ]
    for r in range(rows):
        row_data = cells[r*32:(r+1)*32]
        lines.append("    " + ", ".join(f"0x{c:04X}" for c in row_data) + ",\n")
    lines.append("};\n")
    out_path.write_text("".join(lines), encoding="utf-8", newline="\n")

# 14-cycle title fade NES PALRAM states (transcribed from Z_02.asm:1111-1177
# DemoPhase0Subphase1Palettes). Each row is 32 NES palette bytes.
_TITLE_FADE_NES_CYCLES = [
    [0x36, 0x0F, 0x00, 0x10, 0x36, 0x17, 0x27, 0x0F,
     0x36, 0x08, 0x1A, 0x28, 0x36, 0x30, 0x3B, 0x22,
     0x36, 0x30, 0x3B, 0x16, 0x36, 0x17, 0x27, 0x0F,
     0x36, 0x08, 0x1A, 0x28, 0x36, 0x30, 0x3B, 0x22],
    [0x39, 0x0F, 0x00, 0x10, 0x39, 0x17, 0x27, 0x0F,
     0x39, 0x08, 0x1A, 0x28, 0x39, 0x30, 0x3B, 0x22,
     0x39, 0x30, 0x3B, 0x16, 0x39, 0x17, 0x27, 0x0F,
     0x39, 0x08, 0x1A, 0x28, 0x39, 0x30, 0x3B, 0x22],
    [0x31, 0x0F, 0x00, 0x10, 0x31, 0x17, 0x27, 0x0F,
     0x31, 0x08, 0x1A, 0x28, 0x31, 0x30, 0x3B, 0x22,
     0x31, 0x30, 0x3B, 0x16, 0x31, 0x17, 0x27, 0x0F,
     0x31, 0x08, 0x1A, 0x28, 0x31, 0x30, 0x3B, 0x22],
    [0x3C, 0x0F, 0x00, 0x10, 0x3C, 0x17, 0x27, 0x0F,
     0x3C, 0x08, 0x1A, 0x28, 0x3C, 0x30, 0x3B, 0x22,
     0x3C, 0x30, 0x3B, 0x16, 0x3C, 0x17, 0x27, 0x0F,
     0x3C, 0x08, 0x1A, 0x28, 0x3C, 0x30, 0x3B, 0x22],
    [0x3B, 0x0F, 0x00, 0x10, 0x3B, 0x17, 0x27, 0x0F,
     0x3B, 0x08, 0x1A, 0x28, 0x3B, 0x10, 0x3B, 0x22,
     0x3B, 0x10, 0x3B, 0x16, 0x3B, 0x17, 0x27, 0x0F,
     0x3B, 0x08, 0x1A, 0x28, 0x3B, 0x10, 0x3B, 0x22],
    [0x2C, 0x0F, 0x00, 0x10, 0x2C, 0x17, 0x27, 0x0F,
     0x2C, 0x08, 0x1A, 0x28, 0x2C, 0x10, 0x3B, 0x22,
     0x2C, 0x10, 0x3B, 0x16, 0x2C, 0x17, 0x27, 0x0F,
     0x2C, 0x08, 0x1A, 0x28, 0x2C, 0x10, 0x3B, 0x22],
    [0x1C, 0x0F, 0x00, 0x10, 0x1C, 0x17, 0x27, 0x0F,
     0x1C, 0x08, 0x1A, 0x28, 0x1C, 0x10, 0x3B, 0x22,
     0x1C, 0x10, 0x3B, 0x16, 0x1C, 0x17, 0x27, 0x0F,
     0x1C, 0x08, 0x1A, 0x28, 0x1C, 0x10, 0x3B, 0x22],
    [0x02, 0x0F, 0x00, 0x10, 0x02, 0x06, 0x27, 0x0F,
     0x02, 0x0A, 0x1A, 0x18, 0x02, 0x10, 0x2B, 0x12,
     0x02, 0x10, 0x2B, 0x06, 0x02, 0x06, 0x27, 0x0F,
     0x02, 0x0A, 0x1A, 0x18, 0x02, 0x10, 0x2B, 0x12],
    [0x0C, 0x0F, 0x00, 0x10, 0x0C, 0x03, 0x16, 0x0F,
     0x0C, 0x01, 0x0A, 0x08, 0x0C, 0x00, 0x1B, 0x02,
     0x0C, 0x00, 0x1B, 0x02, 0x0C, 0x03, 0x16, 0x0F,
     0x0C, 0x01, 0x0A, 0x08, 0x0C, 0x00, 0x1B, 0x02],
    [0x0F, 0x0F, 0x0F, 0x00, 0x0F, 0x01, 0x11, 0x0F,
     0x0F, 0x0C, 0x01, 0x02, 0x0F, 0x00, 0x01, 0x0C,
     0x0F, 0x00, 0x01, 0x0C, 0x0F, 0x01, 0x11, 0x0F,
     0x0F, 0x0C, 0x01, 0x02, 0x0F, 0x00, 0x01, 0x0C],
    [0x0F, 0x0F, 0x0F, 0x00, 0x0F, 0x01, 0x11, 0x0F,
     0x0F, 0x0F, 0x0C, 0x01, 0x0F, 0x01, 0x0C, 0x0F,
     0x0F, 0x01, 0x0C, 0x0F, 0x0F, 0x01, 0x11, 0x0F,
     0x0F, 0x0F, 0x0C, 0x01, 0x0F, 0x01, 0x0C, 0x0F],
    [0x0F, 0x0F, 0x0F, 0x0F, 0x0F, 0x0F, 0x01, 0x0F,
     0x0F, 0x0F, 0x0F, 0x0C, 0x0F, 0x0C, 0x0F, 0x0F,
     0x0F, 0x0C, 0x0F, 0x0F, 0x0F, 0x0F, 0x01, 0x0F,
     0x0F, 0x0F, 0x0F, 0x0C, 0x0F, 0x0C, 0x0F, 0x0F],
    [0x0F, 0x0F, 0x0F, 0x0F, 0x0F, 0x0F, 0x0F, 0x0F,
     0x0F, 0x0F, 0x0F, 0x0F, 0x0F, 0x0F, 0x0F, 0x0F,
     0x0F, 0x0F, 0x0F, 0x0F, 0x0F, 0x0F, 0x0F, 0x0F,
     0x0F, 0x0F, 0x0F, 0x0F, 0x0F, 0x0F, 0x0F, 0x0F],
    [0x0F, 0x0F, 0x0F, 0x0F, 0x0F, 0x0F, 0x0F, 0x0F,
     0x0F, 0x0F, 0x0F, 0x0F, 0x0F, 0x0F, 0x0F, 0x0F,
     0x0F, 0x0F, 0x0F, 0x0F, 0x0F, 0x0F, 0x0F, 0x0F,
     0x0F, 0x0F, 0x0F, 0x0F, 0x0F, 0x0F, 0x0F, 0x0F],
]
# Compressed delays summing to 230 frames.
_TITLE_FADE_DELAYS = [36, 26, 19, 16, 13, 9, 6, 6, 6, 26, 19, 13, 26, 9]
assert sum(_TITLE_FADE_DELAYS) == 230, f"fade delays sum={sum(_TITLE_FADE_DELAYS)}"

def _build_title_fade_cycles() -> list[list[int]]:
    """Convert each NES 32-byte PALRAM state to 64-word Genesis CRAM."""
    def _cycle_to_cram(nes_pal: list[int]) -> list[int]:
        out = [0] * 64
        for p in range(4):
            for c in range(4):
                out[p*16 + c]     = nes_color_to_gen_cram(nes_pal[p*4 + c])
                out[p*16 + 4 + c] = nes_color_to_gen_cram(nes_pal[16 + p*4 + c])
        return out
    return [_cycle_to_cram(cyc) for cyc in _TITLE_FADE_NES_CYCLES]

def _emit_title_fade(out_path: Path, cycles: list[list[int]],
                     delays: list[int]) -> None:
    """Emit intro_title_fade_cycles[14][64] and intro_title_fade_delays[14]."""
    lines = [
        "/* Auto-generated by tools/extract_intro_assets.py - do not edit. */\n",
        "const unsigned short intro_title_fade_cycles[14][64] = {\n",
    ]
    for i, c in enumerate(cycles):
        lines.append(f"    /* cycle {i} */ {{\n")
        for j in range(0, 64, 8):
            lines.append("        " + ", ".join(f"0x{w:04X}" for w in c[j:j+8]) + ",\n")
        lines.append("    },\n")
    lines.append("};\n\n")
    lines.append("const unsigned short intro_title_fade_delays[14] = {\n    ")
    lines.append(", ".join(str(d) for d in delays))
    lines.append("\n};\n")
    out_path.write_text("".join(lines), encoding="utf-8", newline="\n")

# Triforce glow cycle: Z_02.asm:947 TriforceGlowingColors + delays Z_02.asm:976-983
_TITLE_GLOW_NES_COLORS = [0x27, 0x37, 0x37, 0x27, 0x17, 0x07, 0x07, 0x17]
_TITLE_GLOW_DELAYS     = [6, 6, 6, 6, 6, 6, 6, 16]

def _emit_title_glow(out_path: Path) -> None:
    """Emit intro_title_glow_colors[8] and intro_title_glow_delays[8]."""
    gen = [nes_color_to_gen_cram(c) for c in _TITLE_GLOW_NES_COLORS]
    lines = [
        "/* Auto-generated by tools/extract_intro_assets.py - do not edit. */\n",
        "const unsigned short intro_title_glow_colors[8] = {\n    ",
    ]
    lines.append(", ".join(f"0x{w:04X}" for w in gen))
    lines.append("\n};\n")
    lines.append("const unsigned char intro_title_glow_delays[8] = {\n    ")
    lines.append(", ".join(str(d) for d in _TITLE_GLOW_DELAYS))
    lines.append("\n};\n")
    out_path.write_text("".join(lines), encoding="utf-8", newline="\n")

# ---------------------------------------------------------------------------
# Story-side asset helpers (Task 5)
# ---------------------------------------------------------------------------

def _read_common_bg_chr() -> bytes:
    """CommonBackgroundPatterns.dat -> Genesis 4bpp (color_shift=0)."""
    ref_dir = REPO / "reference" / "aldonunez" / "dat"
    data = (ref_dir / "CommonBackgroundPatterns.dat").read_bytes()
    gen = bytearray()
    for i in range(0, len(data) - 15, 16):
        gen += nes_tile_to_gen_tile(data[i:i+16], color_shift=0)
    return bytes(gen)

def _read_sprite_chr() -> bytes:
    """CommonSpritePatterns + DemoSpritePatterns -> Genesis 4bpp (color_shift=4)."""
    ref_dir = REPO / "reference" / "aldonunez" / "dat"
    data = (ref_dir / "CommonSpritePatterns.dat").read_bytes() + \
           (ref_dir / "DemoSpritePatterns.dat").read_bytes()
    gen = bytearray()
    for i in range(0, (len(data) // 16) * 16, 16):
        gen += nes_tile_to_gen_tile(data[i:i+16], color_shift=4)
    return bytes(gen)

def _read_misc_chr() -> bytes:
    """CommonMiscPatterns.dat -> Genesis 4bpp (color_shift=4)."""
    ref_dir = REPO / "reference" / "aldonunez" / "dat"
    data = (ref_dir / "CommonMiscPatterns.dat").read_bytes()
    gen = bytearray()
    for i in range(0, (len(data) // 16) * 16, 16):
        gen += nes_tile_to_gen_tile(data[i:i+16], color_shift=4)
    return bytes(gen)

def _read_blink_chr() -> bytes:
    """Re-encode heart/rupee/triforce tiles with color_shift=8 for blink anim.

    Output layout (8 NES tiles, 256 bytes Gen 4bpp):
      tile 0-1: NES misc $F2/$F3 (heart top/bot)
      tile 2-3: NES sprite $68/$69 (container heart top/bot)
      tile 4-5: NES sprite $6E/$6F (triforce top/bot)
      tile 6-7: NES sprite $32/$33 (rupee top/bot)
    """
    ref_dir = REPO / "reference" / "aldonunez" / "dat"
    sprite_data = (ref_dir / "CommonSpritePatterns.dat").read_bytes() + \
                  (ref_dir / "DemoSpritePatterns.dat").read_bytes()
    misc_data = (ref_dir / "CommonMiscPatterns.dat").read_bytes()
    misc_base = 0xF2  # CommonMiscPatterns starts at NES tile $F2
    TILES = [
        ("misc",   0xF2, 8),
        ("misc",   0xF3, 8),
        ("sprite", 0x68, 8),
        ("sprite", 0x69, 8),
        ("sprite", 0x6E, 8),
        ("sprite", 0x6F, 8),
        ("sprite", 0x32, 8),
        ("sprite", 0x33, 8),
    ]
    gen = bytearray()
    for source, T, shift in TILES:
        if source == "sprite":
            tile = sprite_data[T*16:(T+1)*16]
        else:
            tile = misc_data[(T - misc_base)*16:(T - misc_base + 1)*16]
        gen += nes_tile_to_gen_tile(tile, color_shift=shift)
    return bytes(gen)

def _build_combined_palette() -> list[int]:
    """Build 64-slot Genesis CRAM combining story BG + sprite palettes.

    Reads the story CRAM (already built by _build_story_cram) and the
    NES sprite palette as PALRAM holds it after the story palette record
    (equal to the capture tools/intro_demo/nes_full/palram_3380.bin this
    replaced), then overlays story color overrides for GANON/ZELDA/LINK.
    """
    story = _build_story_cram()
    cram = list(story)
    # GameCube-version story-scroll color overrides:
    #   pal 1 color 1 = bright red  (GANON)
    #   pal 2 color 1 = rupee blue  (ZELDA)
    #   pal 3 color 1 = bright green (LINK)
    cram[1*16 + 1] = 0x000E   # bright red
    cram[2*16 + 1] = 0x0E88   # rupee blue
    cram[3*16 + 1] = 0x00E0   # bright green
    palram = _nes_palram_after_record(STORY_PALETTE_RECORD)
    # NES sprite palettes $3F10-$3F1F (palram bytes 16-31).
    # Pack into slots 4-7 of Gen pals 1, 2, 3.
    for sp in range(3):
        for c in range(4):
            nes_color = palram[16 + sp * 4 + c]
            cram[(sp + 1) * 16 + 4 + c] = nes_color_to_gen_cram(nes_color)
    return cram

def _emit_combined_palette(out_path: Path, cram: list[int]) -> None:
    lines = [
        "/* Auto-generated by tools/extract_intro_assets.py - do not edit. */\n",
        "/* Layout: slots 0-3 = NES BG palette, slots 4-7 = NES sprite palette. */\n",
        "const unsigned short intro_combined_palette[64] = {\n",
    ]
    for i in range(0, 64, 8):
        lines.append("    " + ", ".join(f"0x{v:04X}" for v in cram[i:i+8]) + ",\n")
    lines.append("};\n")
    out_path.write_text("".join(lines), encoding="utf-8", newline="\n")

# ---------------------------------------------------------------------------
# Story tilemap composition (GameCube version) — ported from
# tools/intro_demo/compose_story_tilemap.py
# ---------------------------------------------------------------------------

_TILE_SPACE  = 0x24
_TILE_PERIOD = 0x63
_TILE_COMMA_GEN  = 512
_TILE_APOSTR_GEN = 513

def _story_tile_for_char(ch: str) -> tuple:
    """Return (tile_idx, is_custom)."""
    if ch == ' ': return (_TILE_SPACE, False)
    if ch == '.': return (_TILE_PERIOD, False)
    if ch == ',': return (_TILE_COMMA_GEN, True)
    if ch == "'": return (_TILE_APOSTR_GEN, True)
    if ch.isdigit(): return (ord(ch) - ord('0'), False)
    if ch.isalpha(): return (0x0A + (ord(ch.upper()) - ord('A')), False)
    return (_TILE_SPACE, False)

def _story_cell(palette: int, tile: int) -> int:
    return ((palette & 3) << 13) | (tile & 0x7FF)

def _vine_l(phase: int) -> int:
    return _story_cell(3, 0xE2 if phase % 2 == 0 else 0xE3)

def _vine_r(phase: int) -> int:
    return _story_cell(3, 0xE3 if phase % 2 == 0 else 0xE2)

def _story_header_row(text: str, pal: int) -> list:
    row = [_story_cell(0, _TILE_SPACE)] * 32
    row[2] = _story_cell(3, 0xE6)
    row[3] = _story_cell(3, 0xE4)
    row[4] = _story_cell(3, 0xE5)
    row[27] = _story_cell(3, 0xE5)
    row[28] = _story_cell(3, 0xE4)
    row[29] = _story_cell(3, 0xE6)
    text = text.upper()
    start = 6 + max(0, (20 - len(text)) // 2)
    for i, ch in enumerate(text):
        if start + i > 25: break
        tile, _ = _story_tile_for_char(ch)
        row[start + i] = _story_cell(pal, tile)
    return row

def _story_body_row(text: str, default_pal: int, pal_overrides: dict, phase: int) -> list:
    row = [_story_cell(0, _TILE_SPACE)] * 32
    row[2] = _vine_l(phase)
    row[29] = _vine_r(phase)
    text = text.upper()
    if len(text) > 25:
        text = text[:25]
    char_pals = [default_pal] * len(text)
    for word, pal in pal_overrides.items():
        word_up = word.upper()
        idx = text.find(word_up)
        while idx >= 0:
            for k in range(len(word_up)):
                if idx + k < len(char_pals):
                    char_pals[idx + k] = pal
            idx = text.find(word_up, idx + 1)
    for i, ch in enumerate(text):
        col = 4 + i
        if col >= 32: break
        tile, _ = _story_tile_for_char(ch)
        row[col] = _story_cell(char_pals[i], tile)
    return row

def _story_empty_vine_row(phase: int) -> list:
    row = [_story_cell(0, _TILE_SPACE)] * 32
    row[2] = _vine_l(phase)
    row[29] = _vine_r(phase)
    return row

def _story_full_vine_row() -> list:
    row = [_story_cell(0, _TILE_SPACE)] * 32
    row[2] = _story_cell(3, 0xE6)
    for c in range(3, 29):
        row[c] = _story_cell(3, 0xE4 if (c - 3) % 2 == 0 else 0xE5)
    row[29] = _story_cell(3, 0xE6)
    return row

_STORY_LINES = [
    "LONG AGO,  GANON,  PRINCE",
    "OF DARKNESS,  STOLE THE",
    "TRIFORCE OF POWER.",
    "PRINCESS ZELDA OF HYRULE",
    "BROKE THE TRIFORCE OF",
    "WISDOM INTO EIGHT PIECES",
    "AND HID THEM FROM GANON",
    "BEFORE SHE WAS KIDNAPPED",
    "BY GANON'S MINIONS.",
    "LINK,  YOU MUST FIND THE",
    "PIECES AND SAVE  ZELDA.",
]

_STORY_OVERRIDES = {
    "GANON":    1,
    "PRINCESS": 2,
    "ZELDA":    2,
    "LINK":     3,
}

def _build_story_tilemap_gc() -> tuple:
    """Build the GameCube-version story tilemap (matches compose_story_tilemap.py)."""
    cells: list = []
    cells.extend(_story_header_row("THE LEGEND OF ZELDA", 1))
    cells.extend(_story_empty_vine_row(0))
    cells.extend(_story_empty_vine_row(1))
    all_lines = _STORY_LINES
    phase = 0
    for i, line in enumerate(all_lines):
        cells.extend(_story_body_row(line, 0, _STORY_OVERRIDES, phase))
        phase += 1
        if i < len(all_lines) - 1:
            cells.extend(_story_empty_vine_row(phase))
            phase += 1
    cells.extend(_story_empty_vine_row(phase))
    phase += 1
    cells.extend(_story_full_vine_row())
    blank_row = [_story_cell(0, _TILE_SPACE)] * 32
    while len(cells) // 32 < 30:
        cells.extend(blank_row)
    rows = len(cells) // 32
    return cells, rows

def _build_treasures_tilemap() -> tuple:
    """Build the treasures tilemap by running compose_treasures_tilemap.py logic.

    Rather than duplicating 400+ lines of tilemap composition logic here, we
    import and call the compose module directly. The intro_demo directory is
    added to sys.path so the relative imports in that module resolve.
    """
    # TODO(Task 6 or later): inline compose_treasures_tilemap.build_tilemap()
    # logic here (or factor to tools/lib/) to remove the runtime dependency
    # on tools/intro_demo/. Importlib bridge is acceptable while intro_demo
    # tree exists; will break silently if intro_demo is ever deleted.
    import sys as _sys
    demo_dir = str(REPO / "tools" / "intro_demo")
    if demo_dir not in _sys.path:
        _sys.path.insert(0, demo_dir)
    import importlib
    compose_mod = importlib.import_module("compose_treasures_tilemap")
    cells, rows = compose_mod.build_tilemap()
    return cells, rows

def main() -> int:
    ap = argparse.ArgumentParser(description="extract intro assets")
    ap.add_argument("--ref-dir", default=str(REPO / "reference" / "aldonunez" / "dat"),
                    help="path to committed disassembly reference data")
    ap.add_argument("--out-dir", default=str(REPO / "data" / "intro"),
                    help="output directory for generated C files")
    ap.add_argument("--verify", action="store_true",
                    help="re-check SHA of emitted files against committed hashes")
    args = ap.parse_args()

    ref_dir = Path(args.ref_dir)
    if not ref_dir.is_dir():
        print(f"error: reference dir not found: {ref_dir}", file=sys.stderr)
        return 2
    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    font_src = ref_dir / "DemoBackgroundPatterns.dat"
    art_src = ref_dir / "DemoSpritePatterns.dat"
    if not font_src.exists() or not art_src.exists():
        print("error: required reference files missing", file=sys.stderr)
        return 2

    font_gen = _load_nes_chr(font_src)
    art_gen  = _load_nes_chr(art_src)
    _emit_chr_array(out_dir / "intro_font_chr.c", "intro_font_chr", font_gen)
    _emit_chr_array(out_dir / "intro_art_chr.c",  "intro_art_chr",  art_gen)

    cram = _build_story_cram()
    _emit_palette(out_dir / "intro_palette.c", cram)

    # Story tilemap: use GameCube-version composition (source of truth per Task 5).
    story_cells, story_rows = _build_story_tilemap_gc()
    if story_rows > 256:
        print(f"error: story tilemap too tall: {story_rows} rows", file=sys.stderr)
        return 2
    _emit_tilemap(out_dir / "intro_story_tilemap.c", "intro_story_tilemap",
                  story_cells, story_rows)

    # NOTE: _build_showcase_tilemap is still called by _build_title_tilemap
    # (Task 4 dedup). The standalone emit was removed in Task 5 cleanup since
    # build.bat no longer compiles intro_showcase_tilemap.c.

    # intro_handoff_state.c removed in Task 8: legacy intro_handoff_state_t
    # struct is gone; intro_start_pressed() replaces intro_handoff().

    # --- Title-screen assets (Task 4) ---
    title_bg_chr = _read_title_bg_chr()
    _emit_chr_array(out_dir / "intro_title_bg_chr.c",
                    "intro_title_bg_chr", title_bg_chr)

    title_sprite_chr = _read_title_sprite_chr()
    _emit_chr_array(out_dir / "intro_title_sprite_chr.c",
                    "intro_title_sprite_chr", title_sprite_chr)

    title_palette_cram = _read_title_palette()
    _emit_title_palette(out_dir / "intro_title_palette.c", title_palette_cram)

    title_cells, title_rows = _build_title_tilemap(ref_dir)
    _emit_title_tilemap(out_dir / "intro_title_tilemap.c", title_cells, title_rows)

    title_fade_cycles = _build_title_fade_cycles()
    _emit_title_fade(out_dir / "intro_title_fade.c",
                     title_fade_cycles, _TITLE_FADE_DELAYS)

    _emit_title_glow(out_dir / "intro_title_glow.c")

    # --- Story-side assets (Task 5) ---
    common_bg_chr = _read_common_bg_chr()
    _emit_chr_array(out_dir / "intro_common_bg_chr.c",
                    "intro_common_bg_chr", common_bg_chr)

    sprite_chr = _read_sprite_chr()
    _emit_chr_array(out_dir / "intro_sprite_chr.c",
                    "intro_sprite_chr", sprite_chr)

    misc_chr = _read_misc_chr()
    _emit_chr_array(out_dir / "intro_misc_chr.c",
                    "intro_misc_chr", misc_chr)

    blink_chr = _read_blink_chr()
    _emit_chr_array(out_dir / "intro_blink_chr.c",
                    "intro_blink_chr", blink_chr)

    combined_palette = _build_combined_palette()
    _emit_combined_palette(out_dir / "intro_combined_palette.c", combined_palette)

    treasures_cells, treasures_rows = _build_treasures_tilemap()
    _emit_tilemap(out_dir / "intro_treasures_tilemap.c",
                  "intro_treasures_tilemap", treasures_cells, treasures_rows)

    emitted = {
        "intro_font_chr.c": _sha(out_dir / "intro_font_chr.c"),
        "intro_art_chr.c":  _sha(out_dir / "intro_art_chr.c"),
        "intro_palette.c": _sha(out_dir / "intro_palette.c"),
        "intro_story_tilemap.c": _sha(out_dir / "intro_story_tilemap.c"),
        "intro_title_bg_chr.c": _sha(out_dir / "intro_title_bg_chr.c"),
        "intro_title_sprite_chr.c": _sha(out_dir / "intro_title_sprite_chr.c"),
        "intro_title_palette.c": _sha(out_dir / "intro_title_palette.c"),
        "intro_title_tilemap.c": _sha(out_dir / "intro_title_tilemap.c"),
        "intro_title_fade.c": _sha(out_dir / "intro_title_fade.c"),
        "intro_title_glow.c": _sha(out_dir / "intro_title_glow.c"),
        "intro_common_bg_chr.c": _sha(out_dir / "intro_common_bg_chr.c"),
        "intro_sprite_chr.c": _sha(out_dir / "intro_sprite_chr.c"),
        "intro_misc_chr.c": _sha(out_dir / "intro_misc_chr.c"),
        "intro_blink_chr.c": _sha(out_dir / "intro_blink_chr.c"),
        "intro_combined_palette.c": _sha(out_dir / "intro_combined_palette.c"),
        "intro_treasures_tilemap.c": _sha(out_dir / "intro_treasures_tilemap.c"),
    }

    hash_file = out_dir / "intro_asset_hashes.txt"
    if args.verify:
        return _verify(emitted, hash_file)
    _write_hashes(emitted, hash_file)
    return 0

def _sha(path: Path) -> str:
    h = hashlib.sha256()
    h.update(path.read_bytes())
    return h.hexdigest()

def _write_hashes(emitted: dict[str, str], hash_file: Path) -> None:
    lines = [f"{sha}  {name}\n" for name, sha in sorted(emitted.items())]
    hash_file.write_text("".join(lines), encoding="utf-8", newline="\n")

def _verify(emitted: dict[str, str], hash_file: Path) -> int:
    if not hash_file.exists():
        print(f"error: hash file missing: {hash_file}", file=sys.stderr)
        return 3
    expected = {}
    for line in hash_file.read_text().splitlines():
        sha, name = line.split("  ", 1)
        expected[name] = sha
    if expected != emitted:
        print("error: emitted SHA set differs from committed", file=sys.stderr)
        return 3
    return 0

if __name__ == "__main__":
    sys.exit(main())
