#!/usr/bin/env python3
"""
Extract DemoTextFields and DemoLineTextAddrs from the NES Zelda 1 ROM.

S2 Phase D1: ports stdout dump to Genesis-ready C-array output under
data/text/.  A --legacy-inc flag is not provided for this extractor because
the original script only printed to stdout; there are no pre-existing .inc
callers.

The NES ROM layout (iNES):
  - 16-byte header
  - 8 PRG banks of $4000 (16KB) each
  - 0 CHR banks (CHR-RAM)

Z_02.asm is PRG bank 2 (swappable bank, mapped at $8000-$BFFF).
Bank 2 file offset = 16 + 2*$4000 = $8010.

We locate the data by pattern-matching the known 48-byte anchor
(DemoStoryFinalSpriteTiles + DemoStoryFinalSpriteAttrs), then read
the DemoTextFields and DemoLineTextAddrs that follow.

Primary outputs (C arrays, data/text/):
  demo_text.c    -- DemoTextFields blob + DemoLineTextAddrs pointer table
  MANIFEST.json  -- schema_version + nes_rom_sha256 + per-block metadata
"""

import argparse
import hashlib
import json
import os
import sys

# Canonical NES ROM SHA256 (locked in spec Section 0 / docs/audit/baseline_rom.md).
NES_ROM_SHA256 = "8f72dc2e98572eb4ba7c3a902bca5f69c448fc4391837e5f8f0d4556280440ac"

HEADER_SIZE = 16
BANK_SIZE = 0x4000
# Z_02.asm is PRG bank 2 (swappable bank, mapped at $8000-$BFFF)
DATA_BANK = 2
DATA_BANK_OFFSET = HEADER_SIZE + DATA_BANK * BANK_SIZE  # 0x08010
DATA_BANK_CPU_BASE = 0x8000

# Known anchor: DemoStoryFinalSpriteTiles (24 bytes) + DemoStoryFinalSpriteAttrs (24 bytes)
ANCHOR = bytes([
    0xE0, 0xE2, 0xEC, 0xEE, 0xF8, 0xFA, 0xE4, 0xE6,
    0xF0, 0xF2, 0xFC, 0xFE, 0xE8, 0xEA, 0xF4, 0xF6,
    0xDC, 0xDE, 0x00, 0x00, 0x78, 0x78, 0x00, 0x00,
    # attrs
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x40, 0x00, 0x00,
])


def sha256_of_file(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def extract_demo_text(rom):
    """Return (text_field_data, line_addr_data) bytes."""
    bank_data = rom[DATA_BANK_OFFSET:DATA_BANK_OFFSET + BANK_SIZE]

    anchor_pos = bank_data.find(ANCHOR)
    if anchor_pos < 0:
        raise ValueError("Anchor pattern (DemoStoryFinalSpriteTiles+Attrs) not found in bank 2")

    text_start = anchor_pos + len(ANCHOR)
    text_cpu = DATA_BANK_CPU_BASE + text_start

    # Find InitDemoSubphaseClearArtifacts by looking for the pattern
    # $20 xx xx $EE xx xx $60 in the bank data after text_start
    end_pos = None
    for i in range(text_start, len(bank_data) - 7):
        if (bank_data[i] == 0x20 and
                bank_data[i + 3] == 0xEE and
                bank_data[i + 6] == 0x60):
            jsr_target = bank_data[i + 1] | (bank_data[i + 2] << 8)
            inc_target = bank_data[i + 4] | (bank_data[i + 5] << 8)
            if jsr_target >= 0x8000 and inc_target < 0x0800:
                end_pos = i
                break

    if end_pos is None:
        raise ValueError("Could not find InitDemoSubphaseClearArtifacts sentinel")

    combined = bank_data[text_start:end_pos]
    total_len = len(combined)

    # Split DemoTextFields from DemoLineTextAddrs.
    # DemoLineTextAddrs entries are 16-bit LE addresses pointing into DemoTextFields.
    # Scan backwards from end to find where DemoLineTextAddrs starts.
    addr_start = total_len

    for i in range(total_len - 2, -1, -2):
        lo = combined[i]
        hi = combined[i + 1]
        addr = lo | (hi << 8)
        if addr >= text_cpu and addr < (text_cpu + total_len):
            addr_start = i
        else:
            break

    text_field_data = bytes(combined[:addr_start])
    line_addr_data = bytes(combined[addr_start:])

    # Sanity: pointer count should match $FF terminator count
    ff_count = text_field_data.count(0xFF)
    num_ptrs = len(line_addr_data) // 2
    if num_ptrs != ff_count:
        raise ValueError(
            f"DemoText pointer count ({num_ptrs}) != $FF terminator count ({ff_count})"
        )

    return text_field_data, line_addr_data


def bytes_to_c_array(data, var_name, bytes_per_line=16):
    size = len(data)
    lines = ["/* Auto-generated by tools/extract_demo_text.py - do not edit. */"]
    lines.append(f"const unsigned long {var_name}_size = {size}UL;")
    lines.append(f"const unsigned char {var_name}[{size}] = {{")
    for i in range(0, size, bytes_per_line):
        chunk = data[i : i + bytes_per_line]
        lines.append("    " + ", ".join(f"0x{b:02X}" for b in chunk) + ",")
    lines.append("};")
    return "\n".join(lines) + "\n"


def write_c_file(path, content):
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(content)
    print(f"  Wrote {path} ({len(content)} bytes)")


def write_demo_text_c(out_dir, text_field_data, line_addr_data):
    """Emit demo_text.c packing both blobs end-to-end."""
    payload = text_field_data + line_addr_data
    content = bytes_to_c_array(payload, "text_demo_text")
    write_c_file(os.path.join(out_dir, "demo_text.c"), content)

    meta = [
        {
            "name": "DemoTextFields",
            "file": "demo_text.c",
            "var_name": "text_demo_text",
            "byte_offset": 0,
            "byte_size": len(text_field_data),
            "ff_terminated_records": text_field_data.count(0xFF),
        },
        {
            "name": "DemoLineTextAddrs",
            "file": "demo_text.c",
            "var_name": "text_demo_text",
            "byte_offset": len(text_field_data),
            "byte_size": len(line_addr_data),
            "entry_count": len(line_addr_data) // 2,
            "format": "u16le_nes_cpu_addr",
        },
    ]
    return meta


def write_manifest(out_dir, all_blocks_meta, rom_sha256):
    """Merge this extractor's blocks into data/text/MANIFEST.json.

    tools/extract_frontend.py writes the same manifest (45 blocks). This
    script used to clobber it wholesale, so whichever ran last won: a full
    builder run left 2 blocks instead of 47 and silently dropped every
    frontend entry. Merging by block name makes the result independent of
    extractor order, which is the only way `python tools/builder/build.py
    <rom>` can be correct regardless of how EXTRACTORS is sequenced.
    """
    path = os.path.join(out_dir, "MANIFEST.json")

    existing = []
    if os.path.exists(path):
        try:
            with open(path, "r", encoding="utf-8") as f:
                prior = json.load(f)
            if isinstance(prior.get("blocks"), list):
                existing = prior["blocks"]
        except (OSError, ValueError) as exc:
            print(f"  WARN: ignoring unreadable {path}: {exc}")

    def key(block):
        # (name, file), not name alone: DemoLineTextAddrs is emitted by both
        # this extractor and extract_frontend.py into different .c files, and
        # keying on name would silently collapse them into one entry.
        return (str(block.get("name", "")), str(block.get("file", "")))

    merged = {key(b): b for b in existing}
    for b in all_blocks_meta:
        merged[key(b)] = b          # this run's blocks win on name collision

    manifest = {
        "schema_version": 1,
        "nes_rom_sha256": rom_sha256,
        "blocks": sorted(merged.values(), key=key),
    }
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        json.dump(manifest, f, indent=2)
        f.write("\n")
    print(f"  Wrote {path} ({len(manifest['blocks'])} blocks, "
          f"{len(all_blocks_meta)} from this run)")


def main():
    parser = argparse.ArgumentParser(
        description="Extract DemoTextFields and DemoLineTextAddrs from NES Zelda to data/text/"
    )
    parser.add_argument(
        "--out-dir",
        default=None,
        help="Output directory for C arrays and MANIFEST.json (default: <repo>/data/text/)",
    )
    args = parser.parse_args()

    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.dirname(script_dir)
    rom_path_env = os.environ.get("ZELDA_NES_ROM", "")
    if rom_path_env and os.path.isfile(rom_path_env):
        rom_path = rom_path_env
    else:
        rom_path = os.path.join(project_root, "Legend of Zelda, The (USA).nes")

    if not os.path.exists(rom_path):
        print(f"ERROR: ROM not found: {rom_path}")
        sys.exit(1)

    rom_sha256 = sha256_of_file(rom_path)
    if rom_sha256 != NES_ROM_SHA256:
        print(f"ERROR: ROM SHA256 mismatch. Expected {NES_ROM_SHA256}, got {rom_sha256}")
        sys.exit(1)

    out_dir = args.out_dir if args.out_dir else os.path.join(project_root, "data", "text")
    os.makedirs(out_dir, exist_ok=True)

    with open(rom_path, "rb") as f:
        rom = f.read()

    print(f"Extracting DemoTextFields from bank 2...")
    text_field_data, line_addr_data = extract_demo_text(rom)

    print(f"\nWriting C-array text data files to {out_dir}...")
    meta = write_demo_text_c(out_dir, text_field_data, line_addr_data)
    write_manifest(out_dir, meta, rom_sha256)

    total = len(text_field_data) + len(line_addr_data)
    print("\n=== Demo text extraction complete ===")
    print(f"  DemoTextFields: {len(text_field_data)} bytes, "
          f"{text_field_data.count(0xFF)} records")
    print(f"  DemoLineTextAddrs: {len(line_addr_data)} bytes, "
          f"{len(line_addr_data) // 2} pointers")
    print(f"  Total: {total} bytes")
    print(f"  Manifest entries: {len(meta)}")
    print(f"  Output directory: {out_dir}")


if __name__ == "__main__":
    main()
