"""Generate original rotating triangle masks; no game art is embedded.

T-284: H32 Window masks use the 96 free pattern slots 1440..1535.
Each frame is independently deduplicated and can be DMA'd from ROM.
Run from any directory; output is deterministic. Python standard library only.
"""
from pathlib import Path
import math

ROOT = Path(__file__).resolve().parents[1]


def generate():
    lines = ['/* Generated by tools/gen_startup_triangle.py; original procedural masks. */']
    counts = []
    for frame in range(46):
        radius = 5.3 * frame if frame <= 14 else 79.5 + 2.7 * (frame - 15)
        angle = -8 * frame if frame <= 14 else -120 - 4 * (frame - 15)
        # Startup Link is (120,141), rendered at y-7 with an 8px half-height.
        vertices = [(128 + radius * math.cos(math.radians(angle + 120 * k)),
                     142 + radius * math.sin(math.radians(angle + 120 * k))) for k in range(3)]
        patterns = [(0xffffffff,) * 8]
        indices = {patterns[0]: 0}
        cells = []
        for ty in range(28):
            for tx in range(32):
                words = []
                for y in range(8):
                    word = 0
                    for x in range(8):
                        px, py = tx * 8 + x + .5, ty * 8 + y + .5
                        cross = [(vertices[(k + 1) % 3][0] - vertices[k][0]) * (py - vertices[k][1])
                                 - (vertices[(k + 1) % 3][1] - vertices[k][1]) * (px - vertices[k][0]) for k in range(3)]
                        inside = frame > 0 and min(cross) >= 0
                        word = (word << 4) | (0 if inside else 15)
                    words.append(word)
                pattern = tuple(words)
                if not any(pattern):
                    cells.append(0)
                else:
                    if pattern not in indices:
                        indices[pattern] = len(patterns)
                        patterns.append(pattern)
                    cells.append(0xe000 | (1440 + indices[pattern]))
        assert len(patterns) <= 96, (frame, len(patterns))
        counts.append(len(patterns))
        lines.append('static const unsigned long tri_patterns_%d[] = {\n%s\n};' %
                     (frame, '\n'.join('    ' + ','.join('0x%08xUL' % v for v in p) + ',' for p in patterns)))
        lines.append('static const unsigned short tri_map_%d[896] = {\n%s\n};' %
                     (frame, '\n'.join('    ' + ','.join('0x%04xu' % v for v in cells[i:i+32]) + ',' for i in range(0,896,32))))
    lines.append('static const triangle_frame_t tri_frames[46] = {')
    lines.extend('    {tri_patterns_%d, tri_map_%d, %du},' % (f, f, n) for f, n in enumerate(counts))
    lines.append('};\n')
    (ROOT / 'src/game/world/startup_triangle_masks.inc').write_text('\n'.join(lines), encoding='ascii')
    print('46 frames; peak %d patterns, %d DMA bytes; 96 reserved slots' % (max(counts), max(counts)*32+1792))


if __name__ == '__main__':
    generate()
