#!/usr/bin/env python3
"""Generate src/game/world/ow_bg_palram_table.c from the ROM's LevelInfoOW.

The NES loads the overworld BG palette from the PPU transfer record at the
start of LevelInfoOW ($3F00, 32 bytes; Z_06.asm LevelInfoOW). Every OW room
shows the same BG PALRAM: the live per-room scan this table used to come
from (tools/parity/probe_nes_ow_bg_palram_full_scan.lua) recorded those 16
bytes for all 128 rooms. Input: reference/aldonunez/dat/LevelInfoOW.dat,
written from the user's ROM by tools/extract_dat_sidecars.py.
"""
from __future__ import annotations

import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
SRC = REPO / "reference" / "aldonunez" / "dat" / "LevelInfoOW.dat"
OUT = REPO / "src" / "game" / "world" / "ow_bg_palram_table.c"


def main() -> int:
    li = SRC.read_bytes()
    if li[:3] != bytes((0x3F, 0x00, 0x20)):
        print(f"{SRC}: expected a $3F00/$20 palette record, got {li[:3].hex()}", file=sys.stderr)
        return 1
    bg = li[3:19]
    row = ", ".join(f"0x{b:02X}" for b in bg)
    lines = [
        "/* Auto-generated by tools/gen_ow_bg_palram_table.py - do not edit.",
        " * NES BG PALRAM $3F00..$3F0F per OW room (LevelInfoOW palette record). */",
        '#include "ow_bg_palram_table.h"',
        "",
        "const unsigned char k_ow_bg_palram_per_room[128][16] = {",
        *(f"    [0x{r:02X}] = {{ {row} }}," for r in range(128)),
        "};",
        "",
    ]
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"wrote {OUT.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
