#!/usr/bin/env python3
"""Generate engine/data/levelinfo_start_rooms.{c,h} from UW manifests.

Reads engine/data/uw_level{N}_quest{Q}_rooms.json files, emits a
data-driven (level, quest) -> start_room_id table that the warp
coordinator consumes. Coordinator code never references a literal
room id; growth = JSON edit + regen + rebuild.

Slice 1 (Task 5.4) emits only L1Q1. Adding rows is intentionally a
follow-up slice: coordinator-side selector resolution stays gated by
manifest membership, so emitting L2-L9 too early would let slice 1
fire on entrances for which UW renderer level/quest setters and door
data have not been verified.

Run from repo root:
    python tools/levelinfo_start_rooms_gen.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
MANIFEST_DIR = REPO / "engine" / "data"
OUT_C = REPO / "engine" / "data" / "levelinfo_start_rooms.c"
OUT_H = REPO / "engine" / "data" / "levelinfo_start_rooms.h"

# Phase B (2026-05-24): full 18-row expansion. L1-L9 x Q1-Q2.
# All manifests verified present at engine/data/uw_level{N}_quest{Q}_rooms.json
# with start_room_id fields populated. The coordinator's `dest_quest`
# is sourced from roomrom_main_current_quest() (src/game/world/quest_dispatch.h)
# rather than hardcoded to 1u; Q2 dungeon-entrance routing requires
# Phase A LBA_B-driven cave_entrance_check to already be landed.
SLICE_1_ENABLED = [
    (1, 1), (1, 2),
    (2, 1), (2, 2),
    (3, 1), (3, 2),
    (4, 1), (4, 2),
    (5, 1), (5, 2),
    (6, 1), (6, 2),
    (7, 1), (7, 2),
    (8, 1), (8, 2),
    (9, 1), (9, 2),
]


def parse_room_id(value) -> int:
    if isinstance(value, int):
        return value
    s = str(value).strip()
    if s.lower().startswith("0x"):
        return int(s, 16)
    return int(s, 10)


def collect_rows() -> list[tuple[int, int, int]]:
    rows: list[tuple[int, int, int]] = []
    for level, quest in SLICE_1_ENABLED:
        manifest = MANIFEST_DIR / f"uw_level{level}_quest{quest}_rooms.json"
        if not manifest.exists():
            sys.exit(f"missing manifest: {manifest}")
        data = json.loads(manifest.read_text(encoding="utf-8"))
        if data.get("level") != level or data.get("quest") != quest:
            sys.exit(
                f"manifest {manifest.name} declares "
                f"level={data.get('level')} quest={data.get('quest')} "
                f"but filename says level={level} quest={quest}"
            )
        room = parse_room_id(data["start_room_id"])
        if not (0 <= room <= 0xFF):
            sys.exit(f"{manifest.name}: start_room_id out of range: {room}")
        rows.append((level, quest, room))
    return rows


HEADER_TEMPLATE = """\
/* Auto-generated by tools/levelinfo_start_rooms_gen.py - do not edit.
 *
 * Data source: engine/data/uw_level{N}_quest{Q}_rooms.json
 *              (start_room_id field).
 *
 * The warp coordinator looks up the destination room for a (level, quest)
 * pair through this table. Slice 1 (Task 5.4) emits only L1Q1 by design;
 * see tools/levelinfo_start_rooms_gen.py SLICE_1_ENABLED for the policy.
 */

#ifndef ROOMROM_LEVELINFO_START_ROOMS_H
#define ROOMROM_LEVELINFO_START_ROOMS_H

struct levelinfo_start_room {
    unsigned char level;
    unsigned char quest;
    unsigned char start_room_id;
};

extern const struct levelinfo_start_room levelinfo_start_rooms[];
extern const unsigned char levelinfo_start_rooms_count;

/* Look up the canonical UW start room for (level, quest).
 * Returns 1 on hit and writes *out_room_id; returns 0 on manifest miss
 * and leaves *out_room_id unchanged. level == 0 (overworld) is always
 * a manifest miss. */
unsigned char levelinfo_start_room_for(unsigned char level,
                                       unsigned char quest,
                                       unsigned char *out_room_id);

#endif /* ROOMROM_LEVELINFO_START_ROOMS_H */
"""


C_PROLOGUE = """\
/* Auto-generated by tools/levelinfo_start_rooms_gen.py - do not edit.
 *
 * Data source: engine/data/uw_level{N}_quest{Q}_rooms.json
 */

#include "levelinfo_start_rooms.h"

const struct levelinfo_start_room levelinfo_start_rooms[] = {
"""


C_EPILOGUE = """\
};

const unsigned char levelinfo_start_rooms_count =
    (unsigned char)(sizeof(levelinfo_start_rooms) /
                    sizeof(levelinfo_start_rooms[0]));

unsigned char levelinfo_start_room_for(unsigned char level,
                                       unsigned char quest,
                                       unsigned char *out_room_id)
{
    unsigned char i;

    if (level == 0u || out_room_id == 0) {
        return 0u;
    }
    for (i = 0u; i < levelinfo_start_rooms_count; i++) {
        if (levelinfo_start_rooms[i].level == level &&
            levelinfo_start_rooms[i].quest == quest) {
            *out_room_id = levelinfo_start_rooms[i].start_room_id;
            return 1u;
        }
    }
    return 0u;
}
"""


def main() -> int:
    rows = collect_rows()
    body_lines = [
        f"    {{ {level}u, {quest}u, 0x{room:02X}u }},  /* L{level}Q{quest} */"
        for (level, quest, room) in rows
    ]
    OUT_H.write_text(HEADER_TEMPLATE, encoding="utf-8")
    OUT_C.write_text(C_PROLOGUE + "\n".join(body_lines) + "\n" + C_EPILOGUE,
                     encoding="utf-8")
    print(f"wrote {OUT_H.relative_to(REPO)}")
    print(f"wrote {OUT_C.relative_to(REPO)}  ({len(rows)} row{'s' if len(rows) != 1 else ''})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
