#!/usr/bin/env python3
"""Generate RoomRom/data/uw_l1q1_cellar_pairs.{c,h} from NES ground truth.

For each cellar id in LevelInfoUW{N}.CellarRoomIdArray, decodes source
room via LevelBlockUW{1,2}Q{1,2}.AttrsA[cellar] / AttrsB[cellar] per
NES Z_05.asm:7264-7278.

Cross-check: at gen time, generator output verified against
RoomRom/tools/uw_reachability.py cellar_targets path. Mismatch fails
build.

Slice-1 emits L1Q1 only. Schema:

    struct uw_cellar_pair {
        unsigned char level;
        unsigned char quest;
        unsigned char source_room_id;
        unsigned char cellar_room_id;
    };

NES rule: AttrsA + AttrsB at the cellar id give the two source rooms
(can be the same; e.g. L1 has AttrsA[$7F] = AttrsB[$7F] = $22). When
they differ, both are valid entry sources; slice-1 emits one row per
distinct (source, cellar) pair.

Run from repo root:
    python tools/uw_cellar_pairs_gen.py
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
DUNGEONS_C = REPO / "data" / "rooms" / "dungeons.c"
OUT_C = REPO / "RoomRom" / "data" / "uw_l1q1_cellar_pairs.c"
OUT_H = REPO / "RoomRom" / "data" / "uw_l1q1_cellar_pairs.h"

# LevelBlock + LevelInfo offsets (mirror data/rooms/dungeons_offsets.h).
LEVELBLOCK_BASES = {
    (1, 1): 0x0000,  # LevelBlockUW1Q1
    (2, 1): 0x0300,  # LevelBlockUW2Q1
    (1, 2): 0x0600,  # LevelBlockUW1Q2
    (2, 2): 0x0900,  # LevelBlockUW2Q2
}
ATTRS_A_REL = 0x00
ATTRS_B_REL = 0x80

LEVELINFO_BASE = 0x0C00
LEVELINFO_BLOCK_BYTES = 0x100
FOE_COUNTS_PATTERN = bytes([0x03, 0x05, 0x06, 0x08])
CELLAR_ARRAY_REL = 0x10
CELLAR_ARRAY_LEN = 10

# Slice-1 emits L1Q1 only.
SLICE_1_TARGETS = [(1, 1)]


def parse_blob() -> bytes:
    text = DUNGEONS_C.read_text(encoding="utf-8")
    return bytes(int(b, 16) for b in re.findall(r"0x([0-9a-fA-F]{2})", text))


def levelblock_base_for(level: int, quest: int) -> int:
    """L1-6 uses UW1, L7-9 uses UW2."""
    block_index = 1 if level <= 6 else 2
    return LEVELBLOCK_BASES[(block_index, quest)]


def levelinfo_base_for(level: int) -> int:
    return LEVELINFO_BASE + (level - 1) * LEVELINFO_BLOCK_BYTES


def find_foe_counts_offset(blob: bytes, level: int) -> int:
    base = levelinfo_base_for(level)
    block = blob[base:base + LEVELINFO_BLOCK_BYTES]
    idx = block.find(FOE_COUNTS_PATTERN)
    if idx < 0:
        sys.exit(f"L{level} FoeCounts pattern not found")
    return idx


def collect_pairs(blob: bytes) -> list[dict]:
    rows = []
    for (level, quest) in SLICE_1_TARGETS:
        fc_off = find_foe_counts_offset(blob, level)
        li_base = levelinfo_base_for(level)
        cellar_array_off = li_base + fc_off + CELLAR_ARRAY_REL
        cellars = blob[cellar_array_off:cellar_array_off + CELLAR_ARRAY_LEN]
        lb_base = levelblock_base_for(level, quest)
        for cellar in cellars:
            if cellar == 0xFF:
                continue
            attrs_a = blob[lb_base + ATTRS_A_REL + cellar]
            attrs_b = blob[lb_base + ATTRS_B_REL + cellar]
            sources = sorted({attrs_a, attrs_b})
            for source in sources:
                rows.append({
                    "level": level,
                    "quest": quest,
                    "source": source,
                    "cellar": cellar,
                })
    return rows


def cross_check_against_reachability(rows: list[dict]) -> None:
    """Verify generator output matches uw_reachability.py cellar_targets.
    For slice-1, just check the cellar id appears in the manifest's
    cellar_targets list."""
    import json
    for (level, quest) in SLICE_1_TARGETS:
        manifest_path = REPO / "RoomRom" / "data" / f"uw_level{level}_quest{quest}_rooms.json"
        if not manifest_path.exists():
            sys.exit(f"missing manifest: {manifest_path}")
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
        manifest_cellars = set()
        for c in manifest.get("cellar_targets", []):
            if isinstance(c, str):
                manifest_cellars.add(int(c, 16) if c.startswith("0x") else int(c, 10))
            else:
                manifest_cellars.add(c)
        gen_cellars = {r["cellar"] for r in rows
                       if r["level"] == level and r["quest"] == quest}
        if gen_cellars != manifest_cellars:
            sys.exit(
                f"cross-check FAIL: L{level}Q{quest} gen cellars {gen_cellars} "
                f"vs manifest cellar_targets {manifest_cellars}"
            )
    print(f"cross-check PASS: cellar set matches manifest cellar_targets")


HEADER_TEMPLATE = """\
/* Auto-generated by tools/uw_cellar_pairs_gen.py - do not edit.
 *
 * UW cellar pairs for slice-1 (L1Q1). Each row maps a UW source room
 * containing a stair tile to the cellar reached via that stair.
 *
 * NES rule: cellar = entry in LevelInfoUW{N}.CellarRoomIdArray;
 *           source = LevelBlockAttrsA[cellar] OR AttrsB[cellar].
 *           Per Z_05.asm:CheckWarps UW branch (line 7264-7282).
 *
 * Cross-checked at gen time vs RoomRom/tools/uw_reachability.py
 * cellar_targets manifest path; mismatch fails build.
 */

#ifndef ROOMROM_UW_L1Q1_CELLAR_PAIRS_H
#define ROOMROM_UW_L1Q1_CELLAR_PAIRS_H

struct uw_cellar_pair {
    unsigned char level;
    unsigned char quest;
    unsigned char source_room_id;
    unsigned char cellar_room_id;
};

extern const struct uw_cellar_pair uw_l1q1_cellar_pairs[];
extern const unsigned char uw_l1q1_cellar_pairs_count;
extern const unsigned char uw_cellar_for_source_lookup[10][3][128];
extern const unsigned char uw_cellar_source_for_cellar_lookup[10][3][128];
extern const unsigned char uw_room_is_cellar_lookup[10][3][128];

/* Lookup helpers — implemented in uw_cellar_meta.c. */

#endif /* ROOMROM_UW_L1Q1_CELLAR_PAIRS_H */
"""


C_PROLOGUE = """\
/* Auto-generated by tools/uw_cellar_pairs_gen.py - do not edit. */

#include "uw_l1q1_cellar_pairs.h"

const struct uw_cellar_pair uw_l1q1_cellar_pairs[] = {
"""


C_EPILOGUE = """\
};

const unsigned char uw_l1q1_cellar_pairs_count =
    (unsigned char)(sizeof(uw_l1q1_cellar_pairs) /
                    sizeof(uw_l1q1_cellar_pairs[0]));
"""


def emit_lookup_array(name: str, table: list[list[list[int]]]) -> str:
    out = ["", f"const unsigned char {name}[10][3][128] = {{"]
    for level in range(10):
        out.append("    {")
        for quest in range(3):
            out.append("        {")
            vals = table[level][quest]
            for i in range(0, 128, 16):
                out.append("            " + ", ".join(f"0x{v:02X}u" for v in vals[i:i + 16]) + ",")
            out.append("        },")
        out.append("    },")
    out.append("};")
    out.append("")
    return "\n".join(out)


def emit_cellar_lookups(rows: list[dict]) -> str:
    source_to_cellar = [[[0xFF for _ in range(128)] for _ in range(3)] for _ in range(10)]
    cellar_to_source = [[[0xFF for _ in range(128)] for _ in range(3)] for _ in range(10)]
    is_cellar = [[[0 for _ in range(128)] for _ in range(3)] for _ in range(10)]
    for r in rows:
        level = r["level"]
        quest = r["quest"]
        source = r["source"]
        cellar = r["cellar"]
        source_to_cellar[level][quest][source] = cellar
        cellar_to_source[level][quest][cellar] = source
        is_cellar[level][quest][cellar] = 1
    return (
        emit_lookup_array("uw_cellar_for_source_lookup", source_to_cellar)
        + emit_lookup_array("uw_cellar_source_for_cellar_lookup", cellar_to_source)
        + emit_lookup_array("uw_room_is_cellar_lookup", is_cellar)
    )


def main() -> int:
    if not DUNGEONS_C.exists():
        sys.exit(f"missing {DUNGEONS_C}")
    blob = parse_blob()
    rows = collect_pairs(blob)
    cross_check_against_reachability(rows)

    body_lines = []
    for r in rows:
        body_lines.append(
            f"    {{ {r['level']}u, {r['quest']}u, "
            f"0x{r['source']:02X}u, 0x{r['cellar']:02X}u }},"
            f"  /* L{r['level']}Q{r['quest']} */"
        )
    OUT_H.write_text(HEADER_TEMPLATE, encoding="utf-8")
    OUT_C.write_text(C_PROLOGUE + "\n".join(body_lines) + "\n" + C_EPILOGUE
                     + emit_cellar_lookups(rows),
                     encoding="utf-8")
    print(f"wrote {OUT_H.relative_to(REPO)}")
    print(f"wrote {OUT_C.relative_to(REPO)}  ({len(rows)} row{'s' if len(rows) != 1 else ''})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
