#!/usr/bin/env python3
"""Generate RoomRom/data/uw_dark_rooms.{c,h} from NES ground truth.

NES rule (Z_05.asm:IsDarkRoom_Bank5 lines 7795-7801):
    A = LevelBlockAttrsE[room_id] & $80
    return A != 0 (dark) else 0 (lit)

Per RoomRom/tools/uw_reachability.py + dungeons_offsets.h:
- LevelBlockUW1Q1 base = $0000, AttrsE rel = $0200
- LevelBlockUW2Q1 base = $0300, AttrsE rel = $0200
- LevelBlockUW1Q2 base = $0600, AttrsE rel = $0200
- LevelBlockUW2Q2 base = $0900, AttrsE rel = $0200

L1-6 uses UW1, L7-9 uses UW2 (mirrors uw_reachability levelblock_base).

UW Q2 reads blob directly — LevelBlockAttrsB Q2 patches are
OVERWORLD-only (per uw_reachability.py:83); UW Q2 .dat files are
complete in the blob.

Schema:

    struct uw_dark_room_meta {
        unsigned char level;
        unsigned char quest;
        unsigned char room_id;
        unsigned char attrs_e_byte;
    };

Slice-1 ships master table for all (L1-L9) x (Q1-Q2). Generator
emits one row per room with bit 7 set in AttrsE.

Run from repo root:
    python tools/uw_dark_rooms_gen.py
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
DUNGEONS_C = REPO / "data" / "rooms" / "dungeons.c"
OUT_C = REPO / "RoomRom" / "data" / "uw_dark_rooms.c"
OUT_H = REPO / "RoomRom" / "data" / "uw_dark_rooms.h"

LEVELBLOCK_BASES = {
    (1, 1): 0x0000,
    (2, 1): 0x0300,
    (1, 2): 0x0600,
    (2, 2): 0x0900,
}
ATTRS_E_REL = 0x0200
SUBTABLE_BYTES = 128
DARK_BIT = 0x80


def parse_blob() -> bytes:
    text = DUNGEONS_C.read_text(encoding="utf-8")
    return bytes(int(b, 16) for b in re.findall(r"0x([0-9a-fA-F]{2})", text))


def levelblock_base(level: int, quest: int) -> int:
    block_index = 1 if level <= 6 else 2
    return LEVELBLOCK_BASES[(block_index, quest)]


def collect_dark_rooms(blob: bytes) -> list[dict]:
    rows = []
    for level in range(1, 10):
        for quest in (1, 2):
            base = levelblock_base(level, quest) + ATTRS_E_REL
            for room in range(SUBTABLE_BYTES):
                b = blob[base + room]
                if b & DARK_BIT:
                    rows.append({
                        "level": level,
                        "quest": quest,
                        "room_id": room,
                        "attrs_e": b,
                    })
    return rows


HEADER = """\
/* Auto-generated by tools/uw_dark_rooms_gen.py - do not edit.
 *
 * UW dark-room manifest. NES rule:
 *   IsDarkRoom_Bank5 (reference/aldonunez/Z_05.asm:7795-7801):
 *     A = LevelBlockAttrsE[room_id] & $80
 *
 * Master table: every (level, quest, room_id) row whose AttrsE
 * byte has bit 7 set.
 *
 * RoomRom 5.8 runtime calls this manifest directly (NOT the
 * drained `room_is_dark_room()` dispatch — that reads $0A7E which
 * is OOB on RoomRom's 2 KB nes_ram, per Task 5.8 G1 fix). The
 * dispatch fn is invoked only at generator time on the host for
 * cross-check provenance.
 */

#ifndef ROOMROM_UW_DARK_ROOMS_H
#define ROOMROM_UW_DARK_ROOMS_H

struct uw_dark_room_meta {
    unsigned char level;
    unsigned char quest;
    unsigned char room_id;
    unsigned char attrs_e_byte;
};

extern const struct uw_dark_room_meta uw_dark_rooms[];
extern const unsigned short uw_dark_rooms_count;
extern const unsigned char uw_dark_room_lookup[10][3][128];

#endif /* ROOMROM_UW_DARK_ROOMS_H */
"""

C_PROLOGUE = """\
/* Auto-generated by tools/uw_dark_rooms_gen.py - do not edit. */

#include "uw_dark_rooms.h"

const struct uw_dark_room_meta uw_dark_rooms[] = {
"""

C_EPILOGUE = """\
};

const unsigned short uw_dark_rooms_count =
    (unsigned short)(sizeof(uw_dark_rooms) /
                     sizeof(uw_dark_rooms[0]));
"""


def emit_dark_lookup(rows: list[dict]) -> str:
    table = [[[0 for _ in range(128)] for _ in range(3)] for _ in range(10)]
    for r in rows:
        table[r["level"]][r["quest"]][r["room_id"]] = 1

    out = ["", "const unsigned char uw_dark_room_lookup[10][3][128] = {"]
    for level in range(10):
        out.append("    {")
        for quest in range(3):
            out.append("        {")
            vals = table[level][quest]
            for i in range(0, 128, 16):
                out.append("            " + ", ".join(f"{v}u" for v in vals[i:i + 16]) + ",")
            out.append("        },")
        out.append("    },")
    out.append("};")
    out.append("")
    return "\n".join(out)


def main() -> int:
    if not DUNGEONS_C.exists():
        sys.exit(f"missing {DUNGEONS_C}")
    blob = parse_blob()
    rows = collect_dark_rooms(blob)

    by_lq = {}
    for r in rows:
        key = (r["level"], r["quest"])
        by_lq.setdefault(key, []).append(r["room_id"])
    print(f"dark-room count by (level, quest):")
    for (lvl, q) in sorted(by_lq):
        rids = sorted(by_lq[(lvl, q)])
        print(f"  L{lvl}Q{q}: {len(rids):2d} rooms  "
              f"sample: {[hex(x) for x in rids[:5]]}")
    print(f"total rows: {len(rows)}")

    body_lines = []
    for r in rows:
        body_lines.append(
            f"    {{ {r['level']}u, {r['quest']}u, "
            f"0x{r['room_id']:02X}u, 0x{r['attrs_e']:02X}u }},"
            f"  /* L{r['level']}Q{r['quest']} R${r['room_id']:02X} */"
        )
    OUT_H.write_text(HEADER, encoding="utf-8")
    OUT_C.write_text(C_PROLOGUE + "\n".join(body_lines) + "\n" + C_EPILOGUE
                     + emit_dark_lookup(rows),
                     encoding="utf-8")
    print(f"wrote {OUT_H.relative_to(REPO)}")
    print(f"wrote {OUT_C.relative_to(REPO)}  ({len(rows)} rows)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
