#!/usr/bin/env python3
"""Generate engine/data/uw_item_rooms.{c,h} from NES ground truth.

NES rule (Z_05.asm:8169-8222):
  RoomItemId = LevelBlockAttrsE[room] & $1F
  if id == $03: deactivate (sentinel for "no item").
  if AttrsF[room] & $07 in (3, 7): deactivate (boss/foes trigger).
  GetShortcutOrItemXY (Z_01.asm:4002-4020):
    idx = (AttrsF[room] & $30) >> 4
    pos_byte = LevelInfo_ShortcutOrItemPosArray[idx]
    X = pos_byte & $F0
    Y = (pos_byte & $0F) << 4
  if id == $1B (triforce): X -= 8.

Deactivated rooms ARE included in the master table — slice-1 records
the trigger so future slices can wire CheckSecretTrigger reveal logic.
The `active_at_spawn` flag distinguishes immediate-spawn from
trigger-gated.

Per engine/tools/uw_reachability.py:81 SHORTCUT_REL = 0x05 (offset
relative to FoeCounts anchor within LevelInfo block). Per
data/rooms/dungeons_offsets.h ROOMROM_UW_LEVELINFO_FOE_COUNTS_OFFSET[].

Schema:

    struct uw_item_room_meta {
        unsigned char level;
        unsigned char quest;
        unsigned char room_id;
        unsigned char item_id;        /* AttrsE & $1F */
        unsigned char item_x;         /* px (0..F0) */
        unsigned char item_y;         /* px (0..F0) */
        unsigned char trigger;        /* AttrsF & $07 */
        unsigned char active_at_spawn;/* 0=trigger-gated, 1=immediate */
    };

Run from repo root:
    python tools/uw_item_rooms_gen.py
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
DUNGEONS_C = REPO / "data" / "rooms" / "dungeons.c"
OUT_C = REPO / "engine" / "data" / "uw_item_rooms.c"
OUT_H = REPO / "engine" / "data" / "uw_item_rooms.h"

LEVELBLOCK_BASES = {
    (1, 1): 0x0000, (2, 1): 0x0300,
    (1, 2): 0x0600, (2, 2): 0x0900,
}
ATTRS_E_REL = 0x0200
ATTRS_F_REL = 0x0280
LEVELINFO_BASE = 0x0C00
LEVELINFO_BLOCK_BYTES = 0x100

# Per-level FoeCounts offset (mirrors data/rooms/dungeons_offsets.c).
FOE_COUNTS_OFFSET = [0x24] * 9
SHORTCUT_REL = 0x05


def parse_blob() -> bytes:
    text = DUNGEONS_C.read_text(encoding="utf-8")
    return bytes(int(b, 16) for b in re.findall(r"0x([0-9a-fA-F]{2})", text))


def levelblock_base(level: int, quest: int) -> int:
    block_index = 1 if level <= 6 else 2
    return LEVELBLOCK_BASES[(block_index, quest)]


def levelinfo_shortcut_array(blob: bytes, level: int) -> bytes:
    li_base = LEVELINFO_BASE + (level - 1) * LEVELINFO_BLOCK_BYTES
    fc_off = FOE_COUNTS_OFFSET[level - 1]
    sc_off = li_base + fc_off + SHORTCUT_REL
    return blob[sc_off:sc_off + 4]


def collect_item_rooms(blob: bytes) -> list[dict]:
    rows = []
    for level in range(1, 10):
        for quest in (1, 2):
            base = levelblock_base(level, quest)
            attrs_e_off = base + ATTRS_E_REL
            attrs_f_off = base + ATTRS_F_REL
            sc_array = levelinfo_shortcut_array(blob, level)
            for room in range(128):
                e = blob[attrs_e_off + room]
                f = blob[attrs_f_off + room]
                item_id = e & 0x1F
                if item_id == 0 or item_id == 0x03:
                    continue
                trigger = f & 0x07
                pos_idx = (f & 0x30) >> 4
                pos_byte = sc_array[pos_idx]
                x_px = pos_byte & 0xF0
                y_px = (pos_byte & 0x0F) << 4
                if item_id == 0x1B:  # triforce: -8 px X
                    x_px = (x_px - 8) & 0xFF
                active = 0 if trigger in (3, 7) else 1
                rows.append({
                    "level": level, "quest": quest, "room_id": room,
                    "item_id": item_id,
                    "item_x": x_px, "item_y": y_px,
                    "trigger": trigger, "active": active,
                })
    return rows


HEADER = """\
/* Auto-generated by tools/uw_item_rooms_gen.py - do not edit.
 *
 * UW item-room manifest. NES authority (Z_05.asm:8169-8222 +
 * Z_01.asm:GetShortcutOrItemXYForRoom 4002-4020):
 *   item_id = AttrsE[room] & $1F (skip 0 / $03 sentinels)
 *   trigger = AttrsF[room] & $07 (3=last boss, 7=foes-for-item)
 *   pos_idx = (AttrsF[room] & $30) >> 4
 *   pos_byte = LevelInfo_ShortcutOrItemPosArray[pos_idx]
 *   X = pos_byte & $F0, Y = (pos_byte & $0F) << 4
 *   triforce ($1B): X -= 8
 *
 * Master table for L1-L9 x Q1-Q2 (UW Q2 reads blob directly per
 * uw_reachability.py:83 — no OW Q2 patch applied).
 */

#ifndef ROOMROM_UW_ITEM_ROOMS_H
#define ROOMROM_UW_ITEM_ROOMS_H

struct uw_item_room_meta {
    unsigned char level;
    unsigned char quest;
    unsigned char room_id;
    unsigned char item_id;
    unsigned char item_x;
    unsigned char item_y;
    unsigned char trigger;
    unsigned char active_at_spawn;
};

extern const struct uw_item_room_meta uw_item_rooms[];
extern const unsigned short uw_item_rooms_count;
extern const unsigned short uw_item_room_lookup[10][3][128];

/* NES item ids relevant to slice-1. */
#define UW_ITEM_ID_COMPASS    0x16u
#define UW_ITEM_ID_MAP        0x17u
#define UW_ITEM_ID_TRIFORCE   0x1Bu

/* Inventory slots (NES Variables.inc + state/item_state.h). Bytes
 * stored at INVENTORY_VALUE(slot) = nes_ram[$0657 + slot]. */
#define UW_INV_SLOT_COMPASS   16u
#define UW_INV_SLOT_MAP       17u
#define UW_INV_SLOT_TRIFORCE  26u   /* NES InvTriforce at $0671 */

#endif /* ROOMROM_UW_ITEM_ROOMS_H */
"""

C_PROLOGUE = """\
/* Auto-generated by tools/uw_item_rooms_gen.py - do not edit. */

#include "uw_item_rooms.h"

const struct uw_item_room_meta uw_item_rooms[] = {
"""

C_EPILOGUE = """\
};

const unsigned short uw_item_rooms_count =
    (unsigned short)(sizeof(uw_item_rooms) /
                     sizeof(uw_item_rooms[0]));
"""


def emit_item_lookup(rows: list[dict]) -> str:
    table = [[[0 for _ in range(128)] for _ in range(3)] for _ in range(10)]
    for idx, r in enumerate(rows):
        table[r["level"]][r["quest"]][r["room_id"]] = idx + 1

    out = ["", "const unsigned short uw_item_room_lookup[10][3][128] = {"]
    for level in range(10):
        out.append("    {")
        for quest in range(3):
            out.append("        {")
            vals = table[level][quest]
            for i in range(0, 128, 8):
                out.append("            " + ", ".join(f"{v}u" for v in vals[i:i + 8]) + ",")
            out.append("        },")
        out.append("    },")
    out.append("};")
    out.append("")
    return "\n".join(out)


def main() -> int:
    if not DUNGEONS_C.exists():
        sys.exit(f"missing {DUNGEONS_C}")
    blob = parse_blob()
    rows = collect_item_rooms(blob)

    by_lq = {}
    for r in rows:
        key = (r["level"], r["quest"])
        by_lq.setdefault(key, []).append(r)
    print("item-room count by (level, quest):")
    for (lvl, q) in sorted(by_lq):
        active = sum(1 for r in by_lq[(lvl, q)] if r["active"])
        print(f"  L{lvl}Q{q}: total={len(by_lq[(lvl, q)]):3d}  active_at_spawn={active}")
    print(f"total rows: {len(rows)}")

    body_lines = []
    for r in rows:
        body_lines.append(
            f"    {{ {r['level']}u, {r['quest']}u, "
            f"0x{r['room_id']:02X}u, 0x{r['item_id']:02X}u, "
            f"0x{r['item_x']:02X}u, 0x{r['item_y']:02X}u, "
            f"{r['trigger']}u, {r['active']}u }},"
            f"  /* L{r['level']}Q{r['quest']} R${r['room_id']:02X} */"
        )
    OUT_H.write_text(HEADER, encoding="utf-8")
    OUT_C.write_text(C_PROLOGUE + "\n".join(body_lines) + "\n" + C_EPILOGUE
                     + emit_item_lookup(rows),
                     encoding="utf-8")
    print(f"wrote {OUT_H.relative_to(REPO)}")
    print(f"wrote {OUT_C.relative_to(REPO)}  ({len(rows)} rows)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
